- CONTRIBUTING.md
Proposed CONTRIBUTING.md modeled on the version used for the BCDevExchange (devex)
> Create initial CONTRIBUTING.md

- gwells/forms.py
- gwells/static/gwells/css/custom-main.css
- gwells/static/gwells/js/wellsMap.js
- gwells/templates/gwells/activity_submission_detail.html
- gwells/templates/gwells/activity_submission_form.html
- gwells/templates/gwells/base.html
- gwells/templates/gwells/search.html
- gwells/views.py
This pull request comprises my initial work setting up the WellsMap object and putting an interactive map onto the 'Submit Activity' page. The 'Submit Activity' map and attendant functionality is not finished (there are unresolved questions about how to populate the lat/long fields, how to store them, and how to update them, among others), but the patterns are there to build upon.
> Map Infrastructure  and Activity Submission Marker Refinement

- .gitignore
- gwells/forms.py
- gwells/static/gwells/css/custom-main.css
- gwells/static/gwells/js/wellsMap.js
- gwells/templates/gwells/activity_submission_form.html
- gwells/templates/gwells/search.html
This PR comprises several substantive improvements to the functionality of the add-map (which shows up on Page 4 of the Activity Submission page), incorporating product-owner feedback and forward-thinking refactors/additions to the WellsMap module; as well, a map has been placed on the Search page; it currently has extremely limited functionality.
> Improvements to Activity Submission Map and Placement of Search Map

- gwells/static/gwells/js/wellsMap.js
This work comprises almost all of the code quality improvements outlined by the SonarQube engine, with the exception of the complexity and function-length issues for the WellsMap class containing function, which was written in an OOP-style by design. In the future, the class may be refactored into a module that uses the prototype chain, but the application's overall complexity does not require such fine-tuning yet.
> Code Quality Improvements

- navunit/report.bat
- navunit/src/test/groovy/FlowSpecs.groovy
- navunit/src/test/groovy/SearchResultsSpec.groovy
- navunit/src/test/groovy/pages/app/ActivitySubmissionPage.groovy
- navunit/src/test/groovy/pages/app/AdditionalInformationPage.groovy
- navunit/src/test/groovy/pages/external/Disclaimer.groovy
NavUnit Tests for senario 1 of the Search.
> Add Scenario 1 Search BDD Tests

- gwells/templates/gwells/well_detail.html
- navunit/src/test/groovy/SearchResultsS1Spec.groovy
- navunit/src/test/groovy/SearchResultsS2Spec.groovy
Updated the Wells detail html template to add spans with IDs as they were not consistenly applied.
Also finalized the Search Results scripts.
> Testability Improvement and updated test scripts

- navunit/src/test/groovy/Navigation/FlowSpecs.groovy
- navunit/src/test/groovy/Search/SearchResults.groovy
- navunit/src/test/groovy/Search/SearchResultsPagination.groovy
- navunit/src/test/groovy/Search/WellSearch.groovy
- navunit/src/test/groovy/pages/app/SearchPage.groovy
- navunit/src/test/groovy/pages/external/BCWaterResourceAtlas.groovy
And fixes to the scripts to have the test pass.
> Test Script reorg

- navunit/src/test/groovy/Navigation/FlowSpecs.groovy
- navunit/src/test/groovy/Search/SearchResults.groovy
- navunit/src/test/groovy/Search/SearchResultsPagination.groovy
- navunit/src/test/groovy/Search/WellSearch.groovy
- navunit/src/test/groovy/pages/app/SearchPage.groovy
- navunit/src/test/groovy/pages/external/BCWaterResourceAtlas.groovy
Updates to the scripts to try to avoid some of the timing issues we have had. Also I am hard inserting a dependency reference for jquery now, so that this might run of the maven machine instead of the master machine.
> Test Script updates

- gwells/static/gwells/js/wellsMap.js
- navunit/src/test/groovy/Search/SearchResults.groovy
- navunit/src/test/groovy/pages/app/SearchPage.groovy
Also changed the link in the map popup to point to the old well details page.
> Update to search scripts to account for changed database content.

- navunit/Readme.md
- navunit/src/test/groovy/Search/SearchResults.groovy
This will pass when Fieran has fixed the bug.
> new tests added, this test currently fails due to a bug

- gwells/static/gwells/css/custom-main.css
- gwells/templates/gwells/search.html
quick typo fixes in readme
fix for ticket #512 https://trello.com/c/ykXE84pb
> Fixes for ticket #512 - table sort + misc

- gwells/static/gwells/js/wellsMap.js
changed size of marker flag (blue dot) from 3 to 4
> Increased well marker dot size (blue dot). Addressing ticket: #325: https://trello.com/c/MspFPAH3

- gwells/templates/1-Column.html
- gwells/templates/gwells/base.html
- gwells/templates/gwells/search.html
- gwells/templates/gwells/well_detail.html
Fixed bootlint errors #515 https://trello.com/c/BhtXtt9o
> #515 https://trello.com/c/BhtXtt9o boolint errors fixed

- gwells/settings.py
Changing this back to what it was as the original was correct. This does not solve our issue though.
> DEBUG Tests

- navunit/src/test/resources/GebConfig.groovy
SInce we have issues with pointing to the reverse proxied urls.
> pointing back to the openshift machine urls

- gwells/urls.py
Update https://dlvrapps.nrs.gov.bc.ca/groundwater-wells to resolve to the search page instead of the current page starting with "The Drill Experts".
Trello tickets:
[https://trello.com/c/D9zDcr91](https://trello.com/c/D9zDcr91) and
[https://trello.com/c/kOLSx77B](https://trello.com/c/kOLSx77B)
> Change application landing page: https://trello.com/c/D9zDcr91

- gwells/templates/robots.txt
- gwells/urls.py
> robots.txt https://trello.com/c/1zQWncKE

- gwells/templates/gwells/search.html
> Added survey link: https://trello.com/c/AhEO1bag

- gwells/templates/404.html
- gwells/templates/500.html
ticket#547 https://trello.com/c/PM2CCfg7 added 404 and 500
> ticket#547 https://trello.com/c/PM2CCfg7 added 404 and 500

- gwells/templates/404.html
- gwells/templates/500.html
Used absolute paths for referenced files instead of templating
> Used absolute paths for referenced files instead of templating Follow up for #546/547

- gwells/database.py
If we use the options in the database.py our build will fail. I have commented out this line as we need to discuss our direction on this.
> Fix database setting

- .gitignore
- database/scripts/copy-remote-code-tables.sql
- database/scripts/create-xform-gwells-well-ETL-table.sql
- database/scripts/load_db.sh
- database/scripts/populate-gwells-well-from-xform.sql
- database/scripts/populate-xform-gwells-well.sql
- database/scripts/replicate.sql
- database/scripts/setup-replicate.sql
- gwells/models.py
- gwells/templates/gwells/well_detail.html
> Moved to FDW. Importing Drilling Company. Displaying Drilling Company on wells details

- gwells/templates/gwells/well_detail.html
To be able to finish my wells summary test scripts
> Testability updates to the wells summary page.

- gwells/templates/gwells/search.html
[gwells/templates/gwells/search.html](url)
> Automatic jump to map, trello #296

- navunit/src/test/groovy/Search/WellSearch.groovy
Due the the database upgrade, I had to adjust the counts in the script.
> Fixed the counts expected.

- navunit/src/test/groovy/Search/WellDetails.groovy
> Update to counteract the failure in test due to..

- README.md
- gwells/templates/gwells/well_detail.html
The space after the curly brace prevented display of the value.
> Fixed display of well cap in well completion details.

- database/scripts/migrate_screens.sql
Was joining on well_id=well_tag_number now joining on well_id=well_id
> Corrected screen replication script.

- database/cron/db-replicate.sh
As per https://www.postgresql.org/docs/9.6/static/populate.html
> Lessening DB resources during data replication 

- database/cron/db-replicate.sh
- database/scripts/create-xform-gwells-well-ETL-table.sql
- database/scripts/migrate_aquifer_wells.sql
- database/scripts/migrate_casings.sql
- database/scripts/migrate_lithology_descriptions.sql
- database/scripts/migrate_perforations.sql
- database/scripts/migrate_production_data.sql
- database/scripts/migrate_screens.sql
- database/scripts/populate-gwells-well-from-xform.sql
- database/scripts/populate-xform-gwells-well.sql
Refactored and optimized all SQL, but unable to fully test as Openshift Pipeline was down.  If this breaks any functional test, then we can quickly revert back to prior commit:
a55b7bde71f269c98553b4bdf16cae04fa1a23d8
> To workaround DB crash when 'out of space'... 

- gwells/templates/500.html
- gwells/urls.py
Also updated the error500 to create a link for the suggested email address.
> Moved the admin url under the DEBUG section.

- Jenkinsfile
For strange reason, developer pipeline doesn't seem to be pulling and sync'ing correctly.
> Sync w main repo

- database/cron/pre-deploy.sh
.. Due to python migrations during Deploy.
> No Op for now, until we find a way forward on preventing data corruption

- database/cron/db-replicate.sh
- database/cron/post-deploy.sh
- database/scripts/post-deploy.sql
- gwells/migrations/0001_initial.py
Also reversed code (from last commit) for migrate.RunSQL() as it won't work for incremental changes to model.
> Merging Environment variables that control DB replication.

- .gitignore
Added more Visual Studio files and folders to ignore list.
> Ignore VS files and folders.

- database/cron/db-replicate.bat
@rstens  Can you test this puppy out on your local Windows dev?
> 1st crack at a Windows batch file version of db-replicate.sh

- Jenkinsfile-developer
- gwells/templates/gwells/well_detail.html
- gwells/templatetags/verbose_name.py
> Revert "Sync'ing GW local repo with upstream"

- api-tests/registries_api_tests.json
- registries/views.py
Better organization of code (methods and properties) in the API view classes.
> Refactor registries API views.py

- frontend/README.md
- registries/tests.py
Getting cities list with DISTINCT ON is not supported by SQLite so build fails. The test for cities list has been removed
> Remove test for cities list

- registries/models.py
- registries/urls.py
- registries/views.py
fix bugs related to registries models on the admin site (some model string representations had mismatched string format arguments), fixed registries views to handle request=None case (only happens during API schema generation), added registries API schema endpoint
> Registries fixes

- frontend/src/registry/components/RegisterHome.vue
- frontend/src/registry/components/RegisterTable.vue
- frontend/test/unit/specs/RegisterTable.spec.js
- registries/tests.py
- registries/views.py
Small fixes to registries search page to satisfy story requirements
> fixes to Registries search page

- frontend/src/registry/components/RegisterHome.vue
- frontend/test/unit/specs/RegisterHome.spec.js
Also: driller list no longer automatically loads when page is accessed.
> pressing reset button now clears driller list (registries)

- database/code-tables/clear-tables.sql
to avoid accidental wipe of Registries tables.
> Removing auto truncate of prov_state

- functional-tests/src/test/groovy/Navigation/FlowSpecs.groovy
- functional-tests/src/test/groovy/Registry/SearchRegistrySpecs.groovy
- functional-tests/src/test/groovy/pages/app/RegisterPage.groovy
One flow test and on basic searching test. Does not yet search on Pump installers as that data is not there yet. If the data is added the test need to be adjusted as it will fail.
> Registries Tests

- database/code-tables/registries/Registration Action Tracking_Driller.sanitized.csv
- database/code-tables/registries/RegistrationActionTracking_Driller.sanitized.csv
- database/code-tables/registries/RegistrationActionTracking_Pump_Installer.sanitized.csv
- database/code-tables/registries/Removed From Registry.sanitized.csv
- database/code-tables/registries/RemovedFromRegistry.sanitized.csv
- database/code-tables/registries/WellDrillerAndPumpInstaller.sanitized.csv
- database/code-tables/registries/clear-tables.sql
- database/code-tables/registries/data-load-static-codes.sql
- database/code-tables/registries/pump_install_reg.sanitized.csv
- database/code-tables/registries/well_drillers_reg.sanitized.csv
- database/cron/post-deploy.sh
- database/scripts/registries/populate-registries-from-xform.sql
- database/scripts/registries/populate-xforms-registries.sql
where Registries data is incomplete.
> Defaulting Province/State

- functional-tests/src/test/groovy/Search/SearchResults.groovy
- functional-tests/src/test/groovy/Search/WellSearch.groovy
Wells fixtures pass all existing functional tests.
> Created wells fixtures and formatting changes in functional tests

- database/cron/post-deploy.sh
> Undoing attempt to move post-deploy.py to post-lifecycle 

- functional-tests/src/test/groovy/wellsummary/WellDetails.groovy
so revising FT results to match.
> Production data revised Artesian pressure

- api-tests/registries_api_tests.json
"Response time less than 200 ms" Postman test occasionally fails and blocks pipeline
> API tests: remove response time test

- frontend/package.json
- frontend/src/registry/components/people/OrganizationAdd.vue
- frontend/src/registry/components/people/PersonDetail.vue
- frontend/src/registry/components/search/SearchTable.vue
- frontend/test/unit/specs/people/OrganizationAdd.spec.js
* proper author and license in frontend/package.json
* fixed some console errors when loading web app (type errors from referencing objects before they are available)
> Fixes for Registries frontend

- Jenkinsfile-developer
> Revert "add --debug to sonarqube script"

- frontend/src/registry/App.vue
- frontend/src/registry/components/people/PersonDetail.vue
- frontend/src/registry/components/search/SearchHome.vue
- registries/serializers.py
* Registries person detail view with edit button placeholders
* note: edit buttons are grouped according to tables in database to make the initial "mvp" version quicker to produce. May need to be reconciled with wireframes/UX
> Applicant/person detail view (draft)

- frontend/src/common/components/Auth.vue
- frontend/src/registry/components/search/SearchHome.vue
- frontend/src/registry/components/search/SearchTable.vue
- frontend/src/registry/components/search/table-helpers/DrillerCertAuth.vue
- frontend/src/registry/components/search/table-helpers/DrillerOrgAddress.vue
- frontend/src/registry/components/search/table-helpers/DrillerOrganization.vue
- frontend/src/registry/components/search/table-helpers/DrillerSubactivity.vue
- frontend/test/unit/specs/fakePersonList.js
- frontend/test/unit/specs/search/SearchTable.spec.js
- registries/serializers.py
- registries/views.py
* Frontend: Registries search properly displays Organization name and address, and class of driller
* Backend: better filtering of registration and application records that are not approved/active
> Fix organization and classifications display on Registries frontend

- frontend/src/common/components/Header.vue
- gwells/static/gwells/css/custom-main.css
- gwells/static/gwells/css/main.css
- gwells/templates/gwells/well_detail.html
@stephenhillier take note that I pushed a few other changes in already, so you may want to compare against an earlier version of developer to see the full extent of changes.
> Final adjustments to well detail for view and printing

- gwells/static/gwells/css/custom-main.css
- gwells/static/gwells/css/main.css
- gwells/templates/gwells/base.html
- gwells/templates/gwells/well_detail.html
- Fixed padding issue on well detail
- Removed loading of bootstrap from django template, now relying on header to load it.
> Removed padding on well detail page (and fixed double bootstrap load)

- functional-tests/src/test/groovy/Registry/SearchRegistrySpecs.groovy
under we move to Fixtures for Functional Testing.
> skip over Registries tests temporarily

- .gitignore
- app/frontend/src/registry/components/search/SearchHome.vue
Add survey to search page (with temporarily hardcoded link)
> Add survey to Registries search page

- .gitignore
- database/local-dump.sh
- database/oc-restore.sh
- database/pvc-dump.sh
- scripts/Jenkinsfiles/pg_dump
- scripts/Jenkinsfiles/pg_replicate
- setup/setup_osx.sh
Complete and upgrade scripts for new pipeline
+database/pvc-dump.sh - script to dump db into pvc
Jenkinsfile-scripts - updated run back up and handle cleanup
Jenkinsfile-scripts -> /scripts/Jenkinsfiles/cron-pg_dump
+database/local-dump.sh - backup for postgresql container
cron-pg_dump + save DB to var
cron-pg_dump + var for project
cron-pg_dump + comments
cron-pg_dump - removed dir change, simpler
cron-pg_dump -> pg_dump
+scripts/Jenkinsfiles/db_vacuum-replicate - cronjob
dp_dump - updated cron schedule
pg_dump - ensure target is running
oc-dump.sh - removed unused var
oc-restore.sh - db restore script started from oc-dump.sh
oc-restore.sh + check input file exists and is non-empty
oc-dump.sh - extend sleep from 3 to 5 seconds
oc-restore.sh + rsync restore file over
oc-dump.sh - switched …
> Complete scripts and update for new pipeline

- app/frontend/package-lock.json
- app/frontend/package.json
- app/frontend/test/unit/specs/people/Notes.spec.js
Update of npm package dependencies flagged by npm audit
> Update npm dependencies

- app/frontend/src/registry/App.vue
- app/gwells/roles.py
- app/gwells/settings/base.py
- app/gwells/templates/gwells/base.html
- app/gwells/tests.py
- app/nose.cfg
- app/registries/permissions.py
- app/registries/tests.py
- app/registries/views.py
- app/wells/documents.py
- app/wells/minio.py
- app/wells/permissions.py
- app/wells/tests/test_documents.py
- app/wells/urls.py
- app/wells/views.py
API endpoint for querying available files (public and private storage), and endpoint for generating a "pre-signed" link to private documents (i.e. a shareable link to a protected file with a short expiry)
Uses environment variables:
S3_HOST: hostname for public document storage
S3_ROOT_BUCKET: public document storage bucket
S3_PRIVATE_ACCESS_KEY: private storage account
S3_PRIVATE_SECRET_KEY: private storage secret
S3_PRIVATE_HOST: private storage host (must be specified even if same as public storage)
S3_PRIVATE_BUCKET: private storage bucket
> [702] backend link to minio document server

- app/database/scripts/wellsearch/post-deploy.sql
**Before**:
```
gwells=> EXPLAIN (ANALYZE, BUFFERS) select * from bcgs_number  order by bcgs_number ;
QUERY PLAN                                                      
--------------------------------------------------------------------------------------------------
Sort  (cost=1225.78..1260.77 rows=13996 width=52) (actual time=87.583..89.192 rows=13996 loops=1)
Sort Key: bcgs_number
Sort Method: quicksort  Memory: 1480kB
Buffers: shared hit=122
->  Seq Scan on bcgs_number  (cost=0.00..261.96 rows=13996 width=52) (actual time=0.015..2.344 rows=13996 loops=1)
Buffers: shared hit=122
Planning time: 0.084 ms
Execution time: 90.165 ms
(8 rows)
```
**After**:
```
gwells=> EXPLAIN (ANALYZE, BUFFERS) select * from bcgs_number  order by bcgs_number ;
QUERY PLAN …
```
> Additional index to support default order by.

- app/nose.cfg
- app/submissions/serializers.py
- app/wells/serializers.py
- app/wells/stack.py
- app/wells/tests/test_stack.py
Switched to using serializers for well stacking.
> [1130] Using serializers for well stacking

- CONTRIBUTING.md
added a paragraph under pull request for the naming convention.
> [documentation] add instruction for pull request naming convention

- setup/README.md
Hi, I have updated the setup with the change to put the django app in backend folder. I have put the path in front of the cmd to be executed.
Let me know if this makes sense.
Thanks
Alex
> [doc] update with new directory structure

- app/backend/gwells/roles.py
- app/frontend/src/common/store/auth.js
- app/frontend/test/unit/specs/common/store/auth.test.js
- Added unit test
- Removed 'gwells_admin' check (admin should be group in keycloak, not a role)
> [1213] Unit tests for permission

- app/backend/gwells/urls.py
- all submissions/data entry related endpoints conditional on ENABLE_DATA_ENTRY.
> Better use of ENABLE_DATA_ENTRY flag

- app/database/scripts/wellsearch/post-deploy.sql
... for round-tripping of Table/Column metadata.
NOTE: To help, Excel VBA can be used, for example:
```
Sub export_metadata()
'
' export_metadata Macro
' Export comments to SQL ready format.
On Error Resume Next
' Remove "Table" column
Columns("B").EntireColumn.Delete
' Remove COMMENTS columns
Columns("I").EntireColumn.Delete
' Remove extraneous column type/size/optional/default metadata
Columns("C:G").EntireColumn.Delete
' Remove rows w/o description metadata
Columns("C").SpecialCells(xlBlanks).EntireRow.Delete
' Doublequote single quotes to escape it'
Columns("C").Replace "'", "''"
End Sub
```
> Test feasibility of Excel -> SQL -> Database -> SchemaSpy

- app/frontend/src/registry/components/search/SearchTable.vue
- app/frontend/src/registry/components/search/table-helpers/DrillerContactInfo.vue
- app/frontend/test/unit/specs/search/SearchTable.spec.js
Registry search now displays company contact information.
> [1093] change search to display company contact details

- Jenkinsfile
- api-tests/aquifers_api_tests.json
- app/backend/aquifers/models.py
- app/backend/aquifers/serializers.py
- app/backend/aquifers/templates/aquifers/aquifers.html
- app/backend/aquifers/urls.py
- app/backend/aquifers/views.py
- app/backend/gwells/urls.py
- app/frontend/build/webpack.prod.conf.js
- app/frontend/package.json
- app/frontend/src/aquifers/App.vue
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/main.js
- app/frontend/src/aquifers/store/actions.types.js
- app/frontend/src/aquifers/store/index.js
- app/frontend/src/aquifers/store/mutations.types.js
- app/frontend/src/common/components/Header.vue
- app/frontend/test/unit/specs/aquifers/components/Search.spec.js
- app/frontend/test/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
PR is for the following cards:
https://trello.com/c/bQ4Dmmji/1262-epicaquiferdata-search-results-related-to-aquifers-5
https://trello.com/c/nyyr9bgJ/1277-epicaquiferdata-add-link-to-aquifers-in-menu-bar-1
https://trello.com/c/hIzPPnyu/850-epicaquiferdata-search-for-an-aquifer-5
The only tests implemented so far are postman tests. I haven't added any Vue tests yet, waiting for the docker-compose env to settle first.
> Search for an aquifer, add link to aquifers, and search results

- app/backend/gwells/templates/gwells/groundwater_information.html
- app/frontend/src/registry/components/search/SearchHome.vue
> [1315] Fixed links

- app/backend/aquifers/urls.py
- app/backend/aquifers/views.py
- app/backend/gwells/documents.py
- app/backend/wells/tests/test_documents.py
- app/backend/wells/views.py
- app/frontend/src/aquifers/components/Documents.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/test/unit/specs/aquifers/components/View.spec.js
- app/frontend/test/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
Aquifer page now displays related documentation/files stored on S3
> [1264] Aquifer documentation (pdf files)

- app/frontend/src/aquifers/components/Form.vue
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/common/common.scss
- app/frontend/test/unit/specs/aquifers/components/Search.spec.js
- app/frontend/test/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
- app/frontend/test/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
- Added "Showing x or y" to pagination
- Added "At least one search field is required" error message
- Added a blank option to Aquifer dropdown options
- Fixed the print margin problems
- Reordered the Search/Aquifer id search form fields
> Various Fixes to Aquifer work

- app/backend/requirements.txt
- app/backend/wells/management/commands/export.py
- app/frontend/src/wells/components/Exports.vue
- openshift/export-wells.cj.json
- modified cronjob to not run concurrent jobs
- fixed display bug (showing download header when no files present)
- added filters
> [1402 ] Export - filtering and crash

- app/backend/wells/management/commands/export.py
> [1402] Excel export -  added some styling to improve readability

- app/backend/wells/management/commands/export.py
Realized csv files were not being compressed.
> Added comression to zip file

- app/frontend/src/wells/components/Exports.vue
Google analytics on (well) downloads
> [1424] Added ga, using description

- app/backend/wells/models.py
- docker-compose.yml
- openshift/maintenance/README.md
- openshift/scripts/db-drops.sql
- openshift/scripts/oc-dump.sh
- openshift/scripts/oc-restore.sh
@DerekRoberts  Please skim over my updates to the README's
@stephenhillier  Please verify my one-line change on docker-compose file.
thanks!
> Enable spatial DB on docker-compose, clean up documentations.

- openshift/scripts/oc-dump.sh
> Revised dump script to ignore DB-wide spatial_ref_sys table 

- app/backend/requirements.txt
- docker-compose.yml
Alternative fix for the same issue as #1155. Note, although the backend runs with this, I haven't tested any spatial functionality.
> docker-compose change to get the backend running with GDAL

- app/frontend/src/registry/components/people/PersonDetail.vue
- app/frontend/src/submissions/views/SubmissionsHome.vue
- The submissionHome view wasn't refreshing due to it now being under a single page app so a watch variable on $route will reset the page settings and route to the correct page.
> [1696][1695] Fixed Submission/Edit Routing

- Jenkinsfile
Fix double aborts to end failed stages.  Also cleanup of commented out section in Jenkinsfile.
> Bug in Jenkinsfile _openshift() wrapper handling

- app/backend/gunicorn.cfg
> Increasing the timeout even more to find the limit

- app/database/scripts/wellsearch/wells_replication_stored_functions.sql
- added coalesce around possible update related null fields, used created as default
> Fix for Replication on Null Fields

- app/frontend/src/submissions/components/SubmissionForm/Lithology.vue
- app/frontend/src/wells/views/WellDetail.vue
- app/frontend/test/unit/specs/submissions/Lithology.spec.js
* Added default of 10 rows to lithology table in submission and edit views
* Fixed lithology table on well summary to display correct data
> [1702] Lithology Table Additions

- Jenkinsfile
- app/backend/aquifers/tests.py
- app/backend/aquifers/views.py
- app/backend/gwells/management/commands/export_databc.py
- app/backend/gwells/models/common.py
- app/backend/gwells/tests/test_commands.py
- app/backend/registries/views.py
- app/backend/wells/management/commands/export.py
- app/backend/wells/tests/test_gis.py
- app/backend/wells/views.py
- openshift/export.cj.json
- Switched from realtime GeoJSON to pre-created files stored on S3 server
- Changed API to redirect to pre-created files.
- Changed directory for wells export, in order to re-use export bucket for multiple export types
> [1720] DataBC - server pre-rendered JSON

- app/backend/wells/filters.py
- tests/api-tests/wells_search_api_tests.json
Also removed latitude and longitude filters.
> New geom filter point names: sw_lat, sw_long, ne_lat, ne_long

- app/backend/wells/tests/test_wells.py
- app/backend/wells/views.py
This PR fixes the well markers not showing up in the well search
> map locations now use same filter as well search

- app/backend/wells/filters.py
- app/backend/wells/views.py
- app/frontend/src/wells/components/SearchFormBooleanOrRange.vue
- app/frontend/src/wells/components/SearchFormBooleanOrText.vue
- app/frontend/src/wells/components/SearchFormInput.vue
- app/frontend/src/wells/components/SearchFormRadio.vue
- app/frontend/src/wells/components/SearchFormSelect.vue
- app/frontend/src/wells/searchFields.js
- app/frontend/src/wells/views/WellSearch.vue
Follow up to #1183 — finishes adding all of the Advanced Search form functionality, fixes a few bugs.
> [1556] Advanced Search - Search Options

- app/backend/gwells/tests/test_commands.py
Was using the wrong mocks, resulting in data being overwritten on S3!
> Fixed unit test to use correct mocks!

- app/backend/wells/tests/test_wells.py
- app/backend/wells/views.py
- app/frontend/src/App.vue
- app/frontend/src/aquifers/components/Form.vue
- app/frontend/src/aquifers/components/New.vue
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/src/common/components/Header.vue
- app/frontend/src/common/components/PageNotFound.vue
- app/frontend/src/registry/components/search/SearchHome.vue
- app/frontend/src/submissions/components/SubmissionForm/CoordsMap.vue
- app/frontend/src/submissions/views/SubmissionDetail.vue
- app/frontend/src/submissions/views/SubmissionsHome.vue
- app/frontend/src/wells/components/SearchMap.vue
- app/frontend/src/wells/components/SingleWellMap.vue
- app/frontend/src/wells/views/GroundwaterInformation.vue
- app/frontend/src/wells/views/WellDetail.vue
- app/frontend/src/wells/views/WellSearch.vue
- app/frontend/test/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
- app/frontend/test/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
* tie search results table to the current bounds of the map
* fix container width
> [1713] Well search fixes

- app/frontend/src/wells/views/WellSearch.vue
Add analytics events to advanced search screen
> add analytics events to well advanced search

- app/frontend/src/submissions/components/SubmissionForm/Lithology.vue
- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
Lithology input no longer automatically populates dropdown boxes (which can "reset" the dropdown data when coming back to the page or editing a well)
> Fix for lithology input

- app/frontend/src/registry/components/people/ApplicationAddEdit.vue
- app/frontend/src/wells/components/SearchFormBooleanOrRange.vue
- app/frontend/src/wells/components/SearchFormRange.vue
- app/frontend/src/wells/views/WellSearch.vue
Nicole pointed out that the date range on advanced search is extending past the border of the bootstrap card. This PR fixes that and also improves advanced search layout on small screens.
This will require some testing as the ApplicationAddEdit component was previously setting a global date input width, which applied to the entire site.
> Style fixes for Advanced Search

- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
- app/frontend/src/wells/views/WellDetail.vue
- Well finished depth removed from well detail and submission preview
> Well Finished Depth Fix

- app/backend/gwells/models/lithology.py
- app/backend/gwells/views/__init__.py
- app/backend/submissions/serializers.py
- app/backend/submissions/tests.py
- app/backend/wells/serializers.py
- app/frontend/src/submissions/components/SubmissionForm/Casings.vue
- app/frontend/src/submissions/components/SubmissionForm/Owner.vue
- Added asterix to UI, to indicate that city is a required field.
- Added asterix to Drive Shoe, to indicate that it's a required field.
- Fixed some PEP8 issues.
- Added missing exception import.
> [1802] Allow creation of legacy records that are missing drive shoe

- Jenkinsfile
Fixed a couple typos in the Jenkins deployment of the Minio and Postgres backup cronjobs.
> fix issues deploying backups

- app/backend/submissions/models.py
- app/backend/submissions/serializers.py
- app/backend/submissions/tests.py
- app/backend/wells/models.py
- app/backend/wells/stack.py
- app/backend/wells/tests/test_stack.py
- app/frontend/src/submissions/components/SubmissionForm/Liner.vue
Performance increase & optimizations
- Changed stack funtion to not use serializers as much.
- Moved expensive to calculate maps into global constant maps.
- Added lock to cached global variable.
- Added tests.
> [1805] Performance increase & optimizations

- app/backend/registries/fixtures/registries.json
- app/frontend/src/submissions/components/SubmissionForm/PersonResponsible.vue
also added in reg numbers to fixtures for testing.
> [1803] Fixed Pump Installer Registration #

- app/frontend/src/common/common.scss
- app/frontend/src/wells/components/SingleWellMap.vue
- app/frontend/src/wells/views/WellDetail.vue
> [1553] Well Detail Page Print Styling

- app/frontend/src/registry/components/people/PersonEdit.vue
Fix for https://trello.com/c/cX0sQEEl/1912-epicregistry-orc-number-format-1
> Fixed label (ORC Number formatting)

- app/frontend/src/aquifers/components/View.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-542
> Change 'Hydraulically connected' text

- app/frontend/src/aquifers/components/View.vue
- app/frontend/src/common/authenticate.js
- app/frontend/src/registry/components/search/SearchHome.vue
- app/frontend/src/registry/components/search/table-helpers/DrillerContactInfo.vue
- app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue
- app/frontend/src/submissions/views/SubmissionsHome.vue
- app/frontend/src/surveys/views/Surveys.vue
- app/frontend/src/wells/components/BasicSearchForm.vue
- app/frontend/src/wells/components/Exports.vue
- app/frontend/src/wells/components/SearchMap.vue
- app/frontend/src/wells/views/GroundwaterInformation.vue
- app/frontend/src/wells/views/WellDetail.vue
- app/frontend/src/wells/views/WellSearch.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-528
> Opens external links in a new window/tab

- app/frontend/src/aquifers/components/View.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-534
> Moves 'Artesian conditions' to the Well Information section

- app/frontend/src/aquifers/components/Search.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-529
> Scrolls to the top of the aquifer's results

- app/frontend/package-lock.json
- app/frontend/package.json
- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/aquifers/components/View.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-527
Example print PDF:
[Groundwater Wells and Aquifers - Province of British Columbia.pdf](https://github.com/bcgov/gwells/files/3913829/Groundwater.Wells.and.Aquifers.-.Province.of.British.Columbia.pdf)
> Improves print CSS for aquifer summary page

- app/frontend/src/aquifers/components/View.vue
This PR fixes bugs that Lindsay found while testing on staging:
1. Water level analysis = opened in new browser even when the value is 'N/A'
2. Water quality information = opened in new browser even though it was an internal link to well searching.
> Fixing more links

- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/layers.js
1. Moved common layer information into a layers.js file for aquifers.
2. Updated WLS_PWD_LICENCES_SVW layer to WLS_WATER_RIGHTS_LICENCES_SVlayer.
3. Cadastral layer is now selected by default
> Fixed aquifer layers on search map

- app/frontend/src/aquifers/components/View.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-543
> Move "other information" section to bottom

- app/frontend/src/aquifers/components/SingleAquiferMap.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-522
> Aquifer summary map uses same layers as aquifer search map.

- .env
- app/frontend/vue.config.js
- docker-compose.yml
Allows using the staging API as an override by using the API_TARGET environment variable
> Allow env API_TARGET to override API endpoint

- app/frontend/package-lock.json
- app/frontend/package.json
- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/submissions/components/SubmissionForm/CoordsMap.vue
- app/frontend/src/wells/components/SearchMap.vue
- app/frontend/src/wells/components/SingleWellMap.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-523
Adds leaflet-gesture-handling Leaflet plugin to prevent accidental map zooming while trying to scroll the page
> Use leaflet-gesture-handling plugin

- app/backend/aquifers/views.py
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/tests/unit/specs/aquifers/components/Search.spec.js
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-530
Adds ability to search by "any" and "all" matching sections (search check boxes)
> Aquifer search improvements (all and any radios)

- app/backend/aquifers/migrations/0026_auto_20191216_2135.py
- app/frontend/src/aquifers/components/Search.vue
Fixes spelling mistake in PR #1494 which was accidentally merged too soon.
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-685
> Fixes spelling of 'Groundwater surface water interactions' in aquifer resource section

- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/common/components/Header.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-723
Logged in:
Logged out:
> Updates header link text and positions

- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/View.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-536
Adds router links to well details per-well in license table on aquifer summary screen
> Adds well links to license table

- app/frontend/src/aquifers/components/Documents.vue
- app/frontend/src/aquifers/components/Form.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/src/submissions/components/SubmissionForm/Documents.vue
- app/frontend/src/wells/components/Documents.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-548
> Allows uploaded files to be deleted on aquifer edit form

- app/backend/aquifers/models.py
- app/backend/aquifers/views.py
- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/src/common/store/documents.js
- app/frontend/tests/unit/specs/aquifers/components/View.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-790
c293dc151d78.png)
> Improves aquifer edit error messages

- app/backend/submissions/serializers.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-701
> Stores driller information for well decommission submissions

- app/backend/submissions/serializers.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-261
Adds 'internal_comments' to well submission serializers
> Saves internal comments on well submission

- app/frontend/src/common/components/FormInput.vue
- app/frontend/src/common/convertCoordinatesMixin.js
- app/frontend/src/submissions/components/SubmissionForm/Coords.vue
- app/frontend/tests/unit/specs/submissions/Coords.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-482
Replaces Coords.vue input locking & watches with on-input coords conversion logic
> Fixes UTM input bug

- app/frontend/src/aquifers/layers.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-780
> Changes Aquifer Map layer 'Groundwater Licences' to 'Water Licences'

- app/frontend/src/submissions/components/SubmissionForm/Coords.vue
- app/frontend/src/wells/views/WellDetail.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-773
> Save empty well lat lng

- app/frontend/src/wells/views/WellDetail.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-263
> Shows well's sub class on well detail screen

- app/backend/wells/change_history.py
Skips over any `well_activity_type` FieldsProvided key. Fixes bug where new wells were not generating any history JSON.
> Fixes bug with generating well history JSON

- app/frontend/src/aquifers/layers.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-836
> Fixes JS exception when toggling 'Water Licences' layer

- app/frontend/src/submissions/components/SubmissionForm/Coords.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-837
> Fixes bug caused by non-numeric input entered into Coords.vue input boxes

- app/backend/wells/management/commands/export.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-825
> Adds more fields (well's aquifer test data) to export

- app/backend/wells/serializers.py
- app/frontend/src/submissions/components/SubmissionForm/Casings.vue
- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
- app/frontend/tests/unit/specs/submissions/Casings.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-702
Adds a `length_required={true|false}` to the submission/* POST endpoint.
> Allows casing start/end to not be required when length_required=false

- app/backend/submissions/serializers.py
- app/backend/wells/management/commands/legacy_records.py
- app/backend/wells/stack.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-48
The legacy_records command no longer updates well after LEGACY submission created
> Fixes for legacy_records command

- app/backend/submissions/serializers.py
- app/frontend/src/submissions/views/SubmissionDetail.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-900
> Fixes bug where well_cap_type was not shown for legacy records

- app/backend/aquifers/urls.py
- app/backend/aquifers/views.py
- app/frontend/src/bulk/components/BulkAquiferDocuments.vue
- app/frontend/src/bulk/components/BulkHome.vue
- app/frontend/src/common/store/documents.js
- app/frontend/src/router.js
- app/frontend/src/submissions/components/SubmissionForm/Documents.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-532
> Bulk aquifer documents uploading

- app/frontend/src/main.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-933
> Initializes Sentry only when app is loaded at prod URL

- app/backend/wells/migrations/0106_auto_20200116_2327.py
- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-816
> Expire drilling companies

- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-493
> Adds development notes to submission preview

- app/frontend/src/aquifers/components/Documents.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-905
> Highlights documents with 'factsheet' in file name

- app/frontend/src/registry/components/people/OrganizationAdd.vue
- app/frontend/src/registry/components/people/OrganizationEdit.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-38
> Updates organization add/edit form labels to be consistent

- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-492
> Shows all screen info on submission preview

- app/frontend/src/submissions/components/SubmissionForm/Yield.vue
- app/frontend/src/wells/views/WellDetail.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-494
> Shows well yield on summary screen

- app/frontend/src/App.vue
- app/frontend/src/common/components/Header.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-686
> Shows top nav hamburger button toggle on mobile

- app/frontend/src/wells/views/WellDetail.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-745
> Adds link to well licence

- app/backend/aquifers/tests.py
- app/backend/wells/tests/test_wells.py
- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/common/assets/images/shape-polygon-plus.svg
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-525
> Adds title tooltips to Aquifer search map tools

- app/frontend/src/submissions/components/SubmissionForm/WellType.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-872
> Hides well tag number dropdown for construction reports

- app/frontend/src/aquifers/components/Form.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-906
> Adds tooltip to Aquifer advanced mapping knowledge indicators

- app/backend/gwells/views/bulk.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-856?focusedCommentId=278717
> Converts infinite to_depth to None for VerticalAquiferExtent model

- app/backend/aquifers/fixtures/aquifers.json
- app/frontend/src/aquifers/components/BarChart.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/View.spec.js
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
> Changes pie charts to bar charts on aquifer details screen

- app/frontend/src/aquifers/components/BarChart.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-537
> Fixes cut off text on x-axis labels on bar charts

- app/frontend/src/submissions/components/SubmissionForm/Coords.vue
- app/frontend/src/submissions/components/SubmissionForm/PersonResponsible.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-924
> Only overwrites driller_name when drillerSameAsPersonResponsible is true

- app/frontend/src/common/components/BackToTopLink.vue
- app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue
- app/frontend/src/submissions/components/SubmissionForm/AquiferData.vue
- app/frontend/src/submissions/components/SubmissionForm/Backfill.vue
- app/frontend/src/submissions/components/SubmissionForm/Casings.vue
- app/frontend/src/submissions/components/SubmissionForm/ClosureDescription.vue
- app/frontend/src/submissions/components/SubmissionForm/Comments.vue
- app/frontend/src/submissions/components/SubmissionForm/Completion.vue
- app/frontend/src/submissions/components/SubmissionForm/Coords.vue
- app/frontend/src/submissions/components/SubmissionForm/DecommissionInformation.vue
- app/frontend/src/submissions/components/SubmissionForm/Development.vue
- app/frontend/src/submissions/components/SubmissionForm/Documents.vue
- app/frontend/src/submissions/components/SubmissionForm/FilterPack.vue
- app/frontend/src/submissions/components/SubmissionForm/Liner.vue
- app/frontend/src/submissions/components/SubmissionForm/Lithology.vue
- app/frontend/src/submissions/components/SubmissionForm/Location.vue
- app/frontend/src/submissions/components/SubmissionForm/MethodOfDrilling.vue
- app/frontend/src/submissions/components/SubmissionForm/ObservationWellInfo.vue
- app/frontend/src/submissions/components/SubmissionForm/Owner.vue
- app/frontend/src/submissions/components/SubmissionForm/PersonResponsible.vue
- app/frontend/src/submissions/components/SubmissionForm/PublicationStatus.vue
- app/frontend/src/submissions/components/SubmissionForm/Screens.vue
- app/frontend/src/submissions/components/SubmissionForm/WaterQuality.vue
- app/frontend/src/submissions/components/SubmissionForm/WellType.vue
- app/frontend/src/submissions/components/SubmissionForm/WorkDates.vue
- app/frontend/src/submissions/components/SubmissionForm/Yield.vue
- app/frontend/src/submissions/views/SubmissionsHome.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-34
> Fixes submission reload bug when url fragment changes

- app/frontend/src/submissions/components/SubmissionForm/AquiferData.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-884
> Adds units to inputs on well edit's aquifer details section

- app/backend/submissions/serializers.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-492
> Adds screen_information to construction submission serializer

- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-537
> Removes MCM from pie chart labels

- app/backend/wells/management/commands/export.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-958
> Fixes well_subclass in export

- app/backend/wells/change_history.py
- app/backend/wells/stack.py
- app/backend/wells/tests/test_stack.py
- app/frontend/src/common/store/auth.js
- app/frontend/src/submissions/components/SubmissionForm/WellHistory.vue
- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-870
> Shows all well changes in well history

- app/backend/wells/models.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-942
> Better error message for in-use plate numbers

- Jenkinsfile
This PR updates the Jenkinsfile to use the correct netapp-file-standard storage class.
> Update staging deployment config in pipeline to use netapp

- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/aquifers/legend.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-948
> Toggles aquifer wells and raster wells layers together

- app/backend/aquifers/change_history.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-891
> Returns None when 'geom' is missing from reversion fields

- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/wells/components/SearchMap.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-981
> Enhances the fuchia outline around artesian wells

- app/frontend/src/common/components/FormInput.vue
- app/frontend/src/registry/components/people/OrganizationAdd.vue
- app/frontend/src/registry/components/people/OrganizationEdit.vue
- app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue
- app/frontend/src/submissions/components/SubmissionForm/AquiferData.vue
- app/frontend/src/submissions/components/SubmissionForm/Casings.vue
- app/frontend/src/submissions/components/SubmissionForm/ClosureDescription.vue
- app/frontend/src/submissions/components/SubmissionForm/Liner.vue
- app/frontend/src/submissions/components/SubmissionForm/Lithology.vue
- app/frontend/src/submissions/components/SubmissionForm/PublicationStatus.vue
- app/frontend/src/submissions/components/SubmissionForm/Screens.vue
- app/frontend/src/submissions/components/SubmissionForm/WellType.vue
- app/frontend/tests/unit/specs/submissions/ClosureDescription.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-970
> Well edit save button stays disabled when dropdown changed

- app/frontend/src/App.vue
- app/frontend/src/common/helpers/browserUpdate.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1063
> Tweaking CSS & wording of outdated browser message

- app/frontend/src/aquifers/components/ObservationWell.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-838
> Adds error icon to water level analysis if XHR fails

- app/frontend/src/aquifers/components/SingleAquiferMap.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1056
> Adds 'Well Tag Number' to aquifer details map popup

- app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-785
> Browser back goes back in multi-step well submission form

- app/frontend/src/wells/views/WellSearch.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1116
> Fix map id for smooth scrolling selector

- app/frontend/src/aquifers/popup.js
Fixes aquifer map well popup not sticking when EMS / Uncorrelated well layer enabled
> Another aquifer popup fix

- Jenkinsfile
I removed the defunct automatic backup verification step. It was failing silently.
See Jira ticket https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1163
> fixes for pre-deploy backup step

- app/frontend/src/common/mapbox/layers.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1166
> Fixes vector tile server URL syntax

- app/frontend/src/aquifers/popup.js
- app/frontend/src/wells/popup.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1107
> Removes hyperlink from Well Tag Number in well popups

- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/common/mapbox.scss
- app/frontend/src/common/mapbox/images.js
- app/frontend/src/wells/components/SingleWellMap.vue
- app/frontend/src/wells/views/WellDetail.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1159
> Replace Leaftlet with Mapbox GL on Well Summary screen

- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/popup.js
- app/frontend/src/common/assets/images/wells-artesian-search-result.svg
- app/frontend/src/common/assets/images/wells-search-result.svg
- app/frontend/src/wells/components/SearchMap.vue
- app/frontend/src/wells/popup.js
- app/frontend/src/wells/views/WellSearch.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1107
1. Removes the search results icons from legend.
2. Hides popups when map is reset.
3. Fixes grammar of off-current-view message.
> Tweaks for well search map

- Jenkinsfile
- app/backend/aquifers/management/commands/import_licences.py
- app/backend/aquifers/models/__init__.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1115
> Deletes all existing water licences on import

- app/backend/aquifers/management/commands/import_licences.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1115
> Makes import_licences more robust when parsing CSV

- app/frontend/src/common/mapbox/layers.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1183
Screenshot of bug:
> Fix blurry DataBC road tiles when switching environments

- app/backend/aquifers/views_v2.py
- app/backend/wells/views_v2.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1194
> Removes V2 API docs from auto-gen swagger

- app/backend/wells/views_v2.py
- app/frontend/src/bulk/components/BulkAquiferDocuments.vue
- app/frontend/src/bulk/components/BulkHome.vue
- app/frontend/src/bulk/components/BulkWellDocuments.vue
- app/frontend/src/common/components/Plural.vue
- app/frontend/src/common/store/auth.js
- app/frontend/src/router.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1181
> Bulk well documents upload

- app/frontend/src/bulk/components/BulkAquiferDocuments.vue
- app/frontend/src/bulk/components/BulkWellDocuments.vue
- app/frontend/src/common/store/documents.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1181
> Uploads documents in serial to avoid presigned URL timeouts

- app/backend/aquifers/migrations/0035_aquifer_retire_date_20200522_2157.py
- app/backend/wells/migrations/0113_update_tileserver_views_20200528_1413.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-594
> Fix well & aquifer view migration to grant SELECT perms to ftw_reader

- app/frontend/src/aquifers/components/Form.vue
- app/frontend/src/aquifers/components/View.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-594
> Updates messaging for unpubished aquifers

- app/frontend/src/bulk/components/BulkAquiferDocuments.vue
- app/frontend/src/bulk/components/BulkWellDocuments.vue
- app/frontend/src/common/store/documents.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1181?
Also bulk well document upload now warns that files could be overridden.
> Bulk Well and Aquifer screen now strips IDs from file name before upload

- app/backend/aquifers/views_v2.py
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/store/search.js
- app/frontend/tests/unit/specs/aquifers/components/Search.spec.js
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-594
> Fixes aquifer CSV export bug

- app/backend/aquifers/views_v2.py
- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/src/aquifers/store/search.js
- app/frontend/tests/unit/specs/aquifers/components/Search.spec.js
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
- tests/api-tests/aquifers_v2_api_tests.json
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-594
> Adds a 'Show X retired aquifers' checkbox to aquifer search

- Jenkinsfile
- app/backend/aquifers/management/commands/update_demand.py
- app/frontend/src/aquifers/components/Form.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
- openshift/jobs/update-aquifer/update-aquifer.cj.json
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-748
Also removes demand dropdown from Aquifer edit screen.
> Updates aquifer demand calculation nightly

- app/backend/aquifers/management/commands/update_demand.py
- app/backend/aquifers/models/__init__.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-748
> Handles divide by zero possibility in update_demand command

- app/frontend/src/aquifers/components/View.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-748
> Updates calculated well density tooltip text

- app/backend/gwells/settings/__init__.py
- app/backend/registries/models.py
- app/backend/registries/tests.py
- app/backend/registries/urls.py
- app/backend/registries/views.py
- app/backend/registries/views_v2.py
- app/frontend/src/common/helpers/download.js
- app/frontend/src/common/services/ApiService.js
- app/frontend/src/registry/components/search/SearchHome.vue
- app/frontend/src/registry/components/search/SearchTable.vue
- app/frontend/tests/unit/specs/search/SearchHome.spec.js
- app/frontend/tests/unit/specs/search/SearchTable.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-547
> Adds link to XLSX/CSV export of all registry drillers

- app/backend/registries/views_v2.py
Also fixes a 500 error on staging when people don't have an organization.
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-547
> Reorders the columns in the xlsx/csv export

- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/popup.js
- app/frontend/src/common/authenticate.js
- app/frontend/src/common/helpers/download.js
- app/frontend/src/common/mapbox/controls.js
- app/frontend/src/main.js
- app/frontend/src/router.js
- app/frontend/src/wells/components/SearchMap.vue
- app/frontend/src/wells/views/WellSearch.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1257
Also silences errors from IE 11.
> Fixes a bunch of Sentry JS errors.

- app/backend/registries/urls.py
- app/backend/registries/views_v2.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-547
> Uses filter_backends for ListAPIView for csv/xlsx registries export

- Jenkinsfile
- openshift/pg_tileserv/pg_tileserv.dc.yaml
update to use cluster registry stored build from June 10 2020
> update pg_tileserv image

- app/backend/wells/views_v2.py
- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/aquifers/popup.js
- app/frontend/src/common/assets/images/ecocat-water.svg
- app/frontend/src/common/mapbox.scss
- app/frontend/src/common/mapbox/layers.js
- app/frontend/src/common/mapbox/popup.js
- app/frontend/src/wells/components/SearchMap.vue
- app/frontend/src/wells/popup.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1236
> Changes EcCcat to vector layer and adds map EcoCat tooltips

- app/frontend/src/aquifers/components/AquiferMap.vue
- app/frontend/src/aquifers/components/SingleAquiferMap.vue
- app/frontend/src/common/assets/images/ecocat-groundwater.svg
- app/frontend/src/common/mapbox/layers.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1236
> Splits EcoCat into GW and everything else layers.

- app/backend/wells/migrations/0115_update_well_class_indended_water_use_20200616_2027.py
- app/backend/wells/migrations/0116_not_null_well_class_and_intended_water_use_20200619_2053.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-20
> Fixes migration order

- app/frontend/jest.config.js
- app/frontend/src/common/services/__mocks__/ApiService.js
- app/frontend/src/submissions/components/SubmissionForm/WellType.vue
- app/frontend/tests/unit/specs/aquifers/components/View.spec.js
- app/frontend/tests/unit/specs/people/ApplicationDetail.spec.js
- app/frontend/tests/unit/specs/submissions/ActivitySubmissionForm.spec.js
- app/frontend/tests/unit/specs/submissions/Casings.spec.js
- app/frontend/tests/unit/specs/submissions/ClosureDescription.spec.js
- app/frontend/tests/unit/specs/submissions/WellType.spec.js
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-20
> Fix intended water use dropdown

- app/backend/aquifers/views.py
- app/backend/gwells/management/commands/export_databc.py
- app/backend/registries/views_v2.py
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-507
> Consolidates aquifer material categories in GeoJSON

- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-313
> Shows drive shoe status on submission preview

- app/backend/wells/views_v2.py
The well/aquifer intersect feature should check for null geom (aquifer 1143) before running spatial functions.
> well/aquifer intersect: handle case when aquifer has null geom

- app/backend/aquifers/management/commands/import_licences.py
- app/backend/wells/management/commands/export.py
- openshift/ocp4/postgresql.dc.yml
Not just licences associated with an aquifer
Also:  Excel export now populates the licenced_status_code column from the nightly imported licences.
> Ensure all licences for wells are imported

- app/frontend/src/wells/components/AdvancedSearchForm.vue
- app/frontend/src/wells/components/SearchColumnSelect.vue
- app/frontend/src/wells/store/index.js
- app/frontend/src/wells/views/WellSearch.vue
- docker-compose.yml
this was a tough bug to resolve, somehow it's possible to modify the value of the const DEFAULT_COLUMNS in the store, super weird, this is why I removed the [...DEFAULT_COLUMNS]. tested and seems ok now
> Remove DEFAULT_COLUMNS in the store

- app/backend/gwells/middleware.py
- app/backend/requirements.txt
Added the Markup-Escape to the requirements. Made use of newly added library to comply with SonarCloud code scan alert.
> Added Markup-Escape to comply with sonarcloud alerts

- README.md
- openshift/docker/minio/Dockerfile
Updated instructions for local setup of Min.IO
Specified version of Min.IO in docker file to match version used in staging environment.
> Updated ReadMe for local setup

- app/backend/gwells/documents.py
Logging error was previously flagged from sonar cloud. Recreating issue.
> Resolving error from sonar Cloud code scan

- app/backend/gwells/documents.py
- app/backend/wells/views.py
Adding more debugging output to resolve ticket 1812
> Additional info logger and error logger output

- app/backend/aquifers/views_v2.py
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/store/search.js
- Added filter to advanced search for unpublished aquifers
> Feat: advanced search unpublished aquifers

- app/backend/.envrc
- app/backend/gwells/authentication.py
- app/frontend/src/common/authenticate.js
- app/frontend/src/common/store/auth.js
- docker-compose.yml
Reverting bcgov/gwells#1946 as it breaks the API tests at the moment.
> Revert "Point GWELLS at Keycloak Gold"

- app/backend/submissions/views.py
- app/frontend/src/submissions/views/SubmissionsHome.vue
Changelog:
* Ensure that the email regarding drinking water GPS changes includes a clear indication if we are currently in a test environment
> update email notification for test envs

- app/backend/submissions/views.py
* Fix the Python logic for local/dev/test vs. prod as it wasn't properly checking for "true"
> fix to test env check logic

- app/frontend/src/submissions/components/SubmissionForm/Coords.vue
* Update to drinking water warning prompt
> update to modal wording

- .github/PULL_REQUEST_TEMPLATE.md
- .github/labeller.yaml
- .github/workflows/pr-labeller.yaml
- Added a PR Template to repo that will auto-populate PR's
- Added GitHub action to tag new PR's automatically. Better documentation, minimal effort
> [WELLS-N/A] FEATURE** Added PR Labeller and PR Template

- app/backend/requirements.txt
- No longer use most recent version of Minio - revert to `minio==7.1.16` in `requirements.txt` as this version still worked with our current Python and GDAL versions.
> [GWELLS-2004] UPDATE** Update Minio version

- app/backend/gwells/documents.py
- app/frontend/src/aquifers/components/Search.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
- Fixed an issue with the Bootstrap version upgrade and Vue Router and provisioning router links nested in <b-table> tags
- Fixed an exception issue while parsing document names, now correctly catches/allows unexpected naming conventions
> [HOTFIX][NRPTI-2038/2043]** Bug fix for aquifer search link and registry attachments

- app/backend/wells/migrations/0143_attach_attachments_to_wells.py
- rewrote migration for adding attachments table in attempt to reduce memory usage so OpenShift doesn't OOM.
> [GWELLS-2011] HOTFIX** reduce memory consumption in function

- app/frontend/src/aquifers/components/Search.vue
- app/frontend/src/aquifers/components/View.vue
- app/frontend/src/bulk/components/BulkAquiferDocuments.vue
- app/frontend/src/bulk/components/BulkVerticalAquiferExtents.vue
- app/frontend/src/bulk/components/BulkWellAquiferCorrelation.vue
- app/frontend/src/bulk/components/BulkWellDocuments.vue
- app/frontend/src/submissions/components/SubmissionForm/AquiferData.vue
- app/frontend/src/submissions/components/SubmissionForm/PersonResponsible.vue
- app/frontend/src/submissions/components/SubmissionForm/SubmissionHistory.vue
- app/frontend/src/submissions/components/SubmissionForm/VerticalAquiferExtents.vue
- app/frontend/src/submissions/components/SubmissionForm/WellType.vue
- app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
- app/frontend/src/surveys/views/Surveys.vue
- app/frontend/src/wells/views/EditWellAquifers.vue
- app/frontend/src/wells/views/WellDetail.vue
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/Search.spec.js.snap
- app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap
- Updated all instances of `slot` / `slot-scope` being used in application to `v-slot:cell()` due to the bootstrap package upgrade
> [GWELLS-2060] HOTFIX** Change 'slot/slot-scope' to 'v-slot:cell()'

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- app/database/README.md
- Documentation updates focusing on developer setup and prerequisites
> [GWELLS-2082]DOCS** Update README

- app/frontend/src/wells/components/SearchResults.vue
- app/frontend/src/wells/components/mixins/filters.js
- added `sortable` key to existing search fields for more scalable solution
- added conditional to rendering of Ascending Descending button on search results
> [GWELLS-2085] FIX** Add sortable field to search result parameters

- app/backend/aquifers/management/commands/update_aquifer_resource_section_code.py
- app/backend/aquifers/migrations/aquifer_resource_sections.json
- app/backend/aquifers/views_v2.py
- Added Aquifer Parameters to Aquifer search
- Migration added for aquifer_resource_section_code
> [FEATURE][GWELLS-2052] Add Aquifer Parameters to Aquifer search

- app/backend/aquifers/views_v2.py
- Added empty string check to filter out the empty values of hydraulic conductivity
> [HOTFIX][GWELLS-2052] Added empty string check

- .gitignore
- Makefile
- README.md
- app/frontend/package.json
**No functionality changed within app, all changes are purely developer focused**
- Update makefile commands for all things testing related
- add `coverage` folder to git ignore (auto generated test coverage files)
- update Readme to link to Wiki
- update Vue package.json to include testing coverage function
**Wiki edits are not at all part of the PR process, but including a link since its relevant work**
[Wiki Here](https://github.com/bcgov/gwells/wiki/Testing)
> [GWELLS-2139] DEVELOPER FEATURES** update makefile , gitignore, readme, vue packages

- .vscode/launch.json
- README.md
- Add `launch.json` file to .vscode
- Update README to indicate that debug mode is available
> [FEATURE][GWELLS-#2135] - fix debugger mode

- app/backend/aquifers/views_v2.py
> [GWELLS-NA] BUGFIX** put back GeoJSONIterator

- app/backend/aquifers/views_v2.py
- Now using Aquifer Parameters table when filtering Aquifers having wells with aquifer parameters
> [FIX][GWELLS-2154] Use Aquifer Parameters table when filtering Aquifers

- app/backend/wells/filters.py
- Modify how API handles `legal` and `legal_pid` query strings to omit any dashes before filtering results.
> [GWELLS-2128] FEATURE** omit dashes when searching by Parcel Identifier

- app/backend/wells/filters.py
- Fixed keyname that was missing character
> [GWELLS-2128] HOTFIX** correct legal_id to legal_pid

- tests/api-tests/wells_search_api_tests.json
- tests/api-tests/wells_search_v2_api_tests.json
- Tests were expecting entries for wells that don't exist in staging (dummy data vs prod data), This was removed and tests all returned values for correct entries
- Spread out fuzzy searches, since multi-field searching caused failures in Staging, due to larger sample base
> [GWELLS-2175] FIX** update tests to account for multi-field

- tests/api-tests/wells_search_api_tests.json
- tests/api-tests/wells_search_v2_api_tests.json
> Revert "[GWELLS-2175] FIX** update tests to account for multi-field"

- Jenkinsfile
- Jenkinsfile.ocp4
- tests/api-tests/aquifers_v2_api_tests.json
- tests/api-tests/wells_v2_api_tests.json
- Removed V2 test failing in Staging due to scale of response versus the dev branches
- Moved exports testing to be in Dev only to prevent similar situations happening in Dev
- Pointed my Postman instance at the staging API to Look for any more false positives between dev and testing branches
- Added CLI commands to Jenkins file to hopefully print out much more nicely than we're used to seeing 
What we want:
What we got:
> [GWELLS-2177] TESTS** Postman Test edits

- app/frontend/src/wells/components/SearchMap.vue
- Per SO Request, remove Aquifer Parameter Halos from the well search page.
> [GWELLS-2184] FEATURE** Remove Aquifer Parameter Halos from Well Search

- app/frontend/src/registry/components/people/OrganizationEdit.vue
- Updated UI on organizations page to display all registrants for a given organization
- Supplies links directly to page of registrant
- Removed bloat from conditionally rendered button to one button with disabled attribute
- Changed Delete button from Yellow-Orange to Red since it's a destructive action.
**NEW** Zero registrants (Delete enabled)
**NEW** Multiple Registrants, table displayed, button disabled with **advisory**
**OLD**
> [GWELLS-2205] FEATURE** Add table to display registrants organizations

- Jenkinsfile.ocp4
- Remove individual Emails from Jenkins build emails, replace with team email.
> [GWELLS-N/A] Update Jenkins Email list

- app/frontend/src/common/authenticate.js
> Fix keycloak

- Jenkinsfile
- app/frontend/src/main.js
> Pipeline update 3

- app/frontend/src/main.js
> Added a test comment to main.js

- README.md
> Build Bump

- app/frontend/src/main.js
> Removed test comment

- app/frontend/Dockerfile
> Pipeline test 9

- app/frontend/Dockerfile
- app/frontend/package.json
> Added new preview command in package

- app/frontend/Dockerfile
- app/frontend/vite.config.js
- docker-compose.yml
> Changed ports back to 8080

- app/frontend/Dockerfile
> changed preview port to 8080

- app/frontend/vite.config.js
> Allowed hosts

- app/frontend/vite.config.js
> Updated vite config allowed hosts

- app/frontend/vite.config.js
> Updated to https

- app/frontend/vite.config.js
> Removed https

- app/backend/Dockerfile
- openshift/backendBuildConfig.yaml
> Updated backend build config

- openshift/backendBuildConfig.yaml
> Updated build config to pull from backend dockerfile

- app/frontend/src/common/components/Auth.vue
> Keycloak reverted to old init

- app/frontend/src/common/components/Auth.vue
> Updated keycloak init

- app/frontend/src/common/components/Auth.vue
> Updated keycloak

- .github/codeowners
I haven't been useful enough to justify hanging around the CODEOWNERS file!
> chore(ci): revise codeowners

- openshift/frontendBuildConfig.yaml
> Updated backend url

- app/frontend/vite.config.js
> Added backend url to allowed hosts in vite config

- app/backend/Dockerfile
> Exposed port 8000 in backend dockerfile

- app/backend/Dockerfile
- app/frontend/Caddyfile
- docker-compose.yml
- openshift/frontendBuildConfig.yaml
> Caddy work

- app/frontend/Caddyfile
- app/frontend/Dockerfile
- docker-compose.yml
- openshift/frontendDeployConfig.yaml
> Caddy work 3

- app/frontend/Caddyfile
- app/frontend/Dockerfile
- openshift/backendDeployConfigTest.yaml
> Updated caddy content security policy

- app/frontend/Caddyfile
> Updated ports in caddyfile

- app/frontend/Caddyfile
> Removed headers in caddyfile

- app/backend/wells/views.py
> Updated logger

- app/backend/wells/views.py
> added try catches

- app/frontend/src/common/services/ApiService.js
- app/frontend/src/wells/components/SearchResultExports.vue
> Fixed download

- app/frontend/src/wells/components/SearchResultExports.vue
> Removed console.log

- app/frontend/src/registry/components/search/SearchHome.vue
> Fixed driller search bug

- openshift/backendDeployConfigProd.yaml
- openshift/frontendDeployConfigProd.yaml
> Deploy prod 2

- app/frontend/public/env.js
- openshift/frontendBuildConfig.yaml
> Frontend fix

- app/frontend/Caddyfile
- openshift/frontendBuildConfig.yaml
> Updated caddy file to use replace

- app/frontend/Caddyfile
> Removed unused variable in caddyfile

- app/frontend/Caddyfile
> Updated replace in caddyfile

- app/frontend/Caddyfile
- app/frontend/Dockerfile
> Added replace response module

- app/frontend/Caddyfile
> Trying new delimiters in caddyfile

- app/frontend/src/wells/components/SearchMap.vue
> Updated SearchMap

- app/frontend/Caddyfile
- app/frontend/src/common/mapbox/layers.js
> Updated caddy to handle cors

- app/frontend/vite.config.js
> Added URLS to CORS

- app/frontend/Caddyfile
> Updated caddyfile with header for content-type
