bcgov/gwells

gwells/static/gwells/js/coordSync.js
gwells/static/gwells/js/wellsMap.js
gwells/templates/gwells/activity_submission_form.html

This work comprises some minor refactors that nevertheless improve add/edit map functionality. Most substantively, the 'Map It!' and 'Clear Map' buttons have been removed, and CoordSync validation has been clarified so that the validation success callback (i.e., trying to place/move the well pushpin) only responds to user input and not programmatic changes. This allows for a smooth user experience, as a pin is placed and moved on the map whenever valid coordinates are entered, and the coordinates are updated and synched whenever the pin is moved.

Add/Edit Map Refactors

---

gwells/templates/gwells/activity_submission_form.html
gwells/templates/gwells/search.html

This PR resets attribution to the map's default pending a decision on how to handle attribution; also, the search map now draws a rectangle for searched wells but does not restrict the map's panning ability.

Search Map Feedback Refinement and Attribution Reset

---

gwells/static/gwells/js/wellsMap.js
gwells/templates/gwells/search.html

This work represents the compromise position, wherein the wellPushpin has its wellMarker in all maps where the pushpin exists (and the marker can move with the pin), but this special wellMarker has a different outline to the other wells and is also drawn beneath them, so there will be hints when a well is being added/moved onto the location of an extant well.

Returning WellPushpin's WellMarker In All Pushpin Maps

---

gwells/static/gwells/css/custom-main.css
gwells/static/gwells/js/wellsMap.js
gwells/templates/gwells/search.html

This work ensures that, when a user clicks on 'Search Wells In This Area', the extent thus searched is presented back to the user regardless of whether the search returns wells (so a user does not have to re-zoom to the searched extent to make another attempt).

Search Map Preserves Searched Extent on Failure

---

gwells/static/gwells/css/custom-main.css
gwells/static/gwells/js/wellsMap.js

This work comprises a trivial change to the custom controls' CSS, as well as a more in-depth investigation and resolution of the bug Calvin notified me of wherein moving the mouse off of the map during the select-zoom operation plays havoc with the control.
I've added a mouseout event handler for the situation, which attempts to fly the map to the rectangle's bounds when the mouse leaves the map. There appears to be a bug deep within the Leaflet code for the flyToBounds and/or the panTo methods in this case, however, because it generally results in the map moving a bit but not zooming.
The most expedient resolution would be to have mouseouts simply cancel the operation, but I'm open to other ideas for the resolution.

Control Move and Fix for Select Zoom Mouseout Bug

---

gwells/settings.py
gwells/templates/gwells/search.html
navunit/src/test/resources/GebConfig.groovy
requirements.txt

After a night's sleep I found a better way (definitely more elegant) of dealing with the environment variable and the way to get the new url into the wellsmap.js. This eliminates the need for the new component that I had identified and leaves Django more standard.

a more efficient way of dealing with the new environment variable

---

gwells/settings.py
gwells/templates/gwells/base.html
gwells/templates/gwells/index.html
gwells/templates/gwells/search.html
gwells/urls.py
gwells/views.py
navunit/src/test/groovy/Search/WellSearch.groovy
navunit/src/test/groovy/pages/app/WellSummaryPage.groovy
requirements.txt

Eliminates repeated code.
I have added a new library that allow for making system varaiable available for all templates.
https://pypi.python.org/pypi/django-settings-export
This eliminates the need for setting the context for each view for the google analytics switch and others.
The change is in the actual setting.py, the urls, views and several templates.

updates to the way we deal with env variables in our templates

---

gwells/templates/gwells/base.html
gwells/templates/gwells/groundwater_information.html
gwells/templates/gwells/search.html

Update HTML metadata for GWELLS search and Groundwater info pages to improve SEO and appearance in search results.
For https://apps.nrs.gov.bc.ca/gwells/search:
1. Meta description: "Search for and access details on over 100,000 groundwater wells in British Columbia by map or text."
2. Keywords: groundwater wells, ground water, well, British Columbia, water well drilling, geoexchange well, water well, geotechnical well, water supply wells, dewatering wells, injection wells, remediation wells, monitoring wells
For https://apps.nrs.gov.bc.ca/gwells/groundwater-information:
Meta description: "Learn about groundwater wells in B.C.and how to find out more information about them."

GWELLS HTML page Metadata

---

gwells/migrations/0001_initial.py

This allows 'reverseSQL' to rollback the SQL.

Moving post-deploy SQL to out-of-the-box Django RunSQL

---

database/cron/post-deploy.sh

But DOES work when deploying via pipeline.  This can be reverted as it was only meant for the *.bat file that Windows developers would have used during unit testing.

Relative paths don't work in pods auto-deploying.

---

gwells/minioClient.py
gwells/templates/gwells/well_detail.html
gwells/views/WellDetailView.py

To not use any credentials.  Reserve MINIO_ACCESS_KEY and MINIO_SECRET_KEY for authenticated access to our internal Minio S3 Server.   Edits/Additions from our (not yet built) Admin screens to the "publicly viewable S3" will be authenticated via this internal Minio S3 Server, and it will have stored proxy IAM credentials to the cloud S3.

Refactored Minio Access to public S3

---

sonar-runner/README.md
sonar-runner/build.gradle

Current sonar-runner does not update build numbers, so a historical trend is not built up.
With this change we create a version based on Date and the Jenkins Build number.
YYYYMMDD.XXX example 20180123.132.

Update Sonar-runner to correctly show version numbers. (date.build)

---

registries/tests.py

Test for manage.py createtestuser can fail if the environment variables used to create the test user are not set

remove problem test (false positive if env variable missing)

---

api-tests/registries_api_tests.json
frontend/src/common/services/gwells.js
registries/urls.py

Add version 'v1' to registries API urls. Any future breaking changes to API endpoints will be under a new version.
Also updated API tests and frontend app to use the new URLs.

add version to Registries API urls

---

Jenkinsfile-developer

The nodes that we are using are now defined in the Jenkinsfile instead of needing a definition in Jenkins.

Jenkinsfile changes to eliminate Node defs in Jenkins

---

database/scripts/db_replicate.sql

To avoid 'Past EOF' database error.

Hot Patch - break out db_replicate() into two distinct steps

---

gwells/database.py
gwells/settings/__init__.py
gwells/settings/base.py
gwells/urls.py

Reverted DATABASE_NAME logic, accepting default values, but not None values.
The following is required (no default values allowed):
DJANGO_ADMIN_URL
DJANGO_ADMIN_USER
ENABLE_DATA_ENTRY
ENABLE_GOOGLE_ANALYTICS
ENABLE_ADDITIONAL_DOCUMENTS
S3_HOST
S3_ROOT_BUCKET

Environment variables - 

---

database/cron/post-deploy.sh
gwells/management/commands/post-deploy.py

As putting it in the mid-lifecycle hook returned:
python: error while loading shared libraries: libpython3.5m.so.rh-python35-1.0: cannot open shared object file: No such file or directory

Moving Django command execution for post-lifecycle from mid-lifecycle

---

Jenkinsfile-developer

Switching to an environment variable GWELLS_API_BASE_URL (used only for Postman API tests) caused API tests to fail. Reverted back to hardcoded url (the old way) until we fix the environment variable

Switch back to hardcoded url for API tests

---

registries/models.py
registries/serializers.py
registries/views.py

- Added update to ApplicationAdminSerializer to allow for put/patch requests.
- Added Apache license to a few files.
Example post body to {{base_url}}/api/v1/applications/{{created_application_guid}}/?format=json:
`{
"subactivity": "GEOTECH",
"current_status": {
"status": "P"
}
}`

Added serialization for RegistrationApplication

---

gunicorn.cfg

as the Code Quality check was still running after 3 hours, instead of the usual 2 minutes.  https://jenkins-moe-gwells-tools.pathfinder.gov.bc.ca/job/moe-gwells-tools-gwells-pipeline-developer/494/console

up'ing gunicorn workers 

---

app/frontend/src/registry/components/people/PersonDetail.vue
app/frontend/src/registry/components/search/SearchHome.vue
app/gwells/serializers.py
app/gwells/urls.py
app/gwells/views/APIViews.py

Backend: 
* added a read-only API endpoint at gwells/api/v1/surveys/ that returns a list of currently enabled surveys
Frontend:
* Registries search page checks for active surveys and displays them at the top of the page.
* Minor fix: The company "add/change" button on the driller profile page now only says "add" or "change" depending on if the person has a company or not.

Link up Registries survey display to survey admin tool

---

openshift/backend.dc.json

Fail not causing pipeline to stop.  "Deploy - DEV" has been waiting for 45 minutes on a silently failing script, which is definitely not good feedback for a developer.

[1030] Pipeline abort on mid-cycle fail (Deploy - DEV)

---

app/gwells/fixtures/gwells-codetables.json

To the province state code table, via the fixture.  DB will have these entries:
```
gwells=> select province_state_code, description, display_order from province_state_code order by display_order;
province_state_code |        description        | display_order 
---------------------+---------------------------+---------------
BC                  | British Columbia          |             2
AB                  | Alberta                   |             4
ON                  | Ontario                   |             6
MB                  | Manitoba                  |             8
SK                  | Saskatchewan              |            10
NL                  | Newfoundland and Labrador |            12
NS                  | Nova Scotia               |            14
NT                  | …
```

[1043] Added additional provinces and U.S. states 

---

Jenkinsfile

* disabled parallel testing for Python unit tests
* added `set -e` to script that kicks off tests (exit with error on failing tests)

[1037] Fix for Python unit tests and false positive pipeline status at test stage

---

app/frontend/src/registry/components/search/SearchTable.vue
app/frontend/src/registry/components/search/table-helpers/DrillerContactInfo.vue

* remove conditional check for the contact_info array on the contact info display component (we no longer store contact info as an array)

[1086] Fix display of contact info if contact_detail table is empty

---

app/frontend/src/registry/components/people/ApplicationAddEdit.vue
app/frontend/src/registry/components/people/ApplicationDetail.vue
app/frontend/src/registry/components/people/PersonDetail.vue

* removed references to drilling (like "qualified to drill") from Well Pump Installer classifications
* (minor bug) clear loading state if form submission failed (for example, on a bad request due to too many characters in an input box)

[1000] Minor changes to classification detail/edit

---

.gitignore

Correcting this, as it has already caused issues once when I accidentally .gitignored 'src'

Removed my local gitignores that should not have been in global

---

app/registries/fixtures/registries-codetables.json

Next time, we'll include such new code table values to a Django migration step.  For now, we'll update in-place the existing code table fixture and run on TEST and then PROD:
```
INSERT INTO registries_accredited_certificate_code (
acc_cert_guid,name
,description
,cert_auth_code
,registries_activity_code
,create_user
,create_date
,update_user
,update_date
,effective_date
)
VALUES (
'55911754-e547-4ca0-aad4-29592285f55d'
,'Earth Loop Technician, Alberta Journeyman Certificate'
,null
,'AB'
,'DRILL'
,'DATALOAD_USER'
,'2018-07-27T08:00:00Z'
,'DATALOAD_USER'
,'2018-07-27T08:00:00Z'  
,'1970-01-01')
;
```

[1192] Update Registries fixture to have new Accreditation.

---

setup/README.md

correct a typo in the loaddata cmd for restoring data.

correct typo in loaddata cmd

---

app/frontend/src/registry/components/search/SearchTable.vue
app/frontend/test/unit/specs/search/SearchTable.spec.js

Hi, 
I have added a watch on the drillers to scroll to the top of the table using $smoothScroll ext lib as it is already part of the solution packages.
I know watch should be avoided but in that case I found it suitable to use (learning vue)
also I did a bit of refactoring on the paginationNext/Previous as my first attempt to do the scroll was in the methods...
I'm not sure of the behavior and whether user will like it.
I could not figure out yet how to unit test the watch, I tried multiple approach with spy but couldn't make it trigger...
Let me know what you think...

[947] epicregistry-jump-after-next-button-selected-1

---

app/backend/gwells/static/gwells/css/main.css
app/backend/wells/templates/wells/well_detail.html

Hi,
I have added the quick links on the wells details page. I did my best for it to look ok and to add as minimum as I could. it was not specified anything for mobile so I left it resized as the other columns...
Couple of suggestion:
* lots of repetition in the well-details template (I've added more 😄 ), could be refactored to create small reusable elements...
* the main.css file is huge, I have put my changes at the bottom, there is also lot of repetition that makes it hard to follow.
* the css should be applied by classes, it is difficult when it changes the rendering of base elements. e.g. bootstrap behavior is changed...
Let me know what you think ;-)
Alex

[650] epicwellsummary jump links 3

---

app/frontend/src/submissions/components/SubmissionForm/Coords.vue

Due do the different way that browsers handle "number" fields, it's easier to just stick with a "text" type, and have Vue.js bind to text as a number.

[1368] Changed lat/long to "text" input fields

---

app/backend/aquifers/serializers.py

This returns the Subtype code and description as the description, which is how users expect the subtype represented.

Use __str__ for subtype description because it includes the code

---

app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue
app/frontend/src/submissions/components/SubmissionPreview/SubmissionPreview.vue
app/frontend/src/submissions/views/SubmissionsHome.vue
app/frontend/test/unit/specs/submissions/SubmissionsHome.spec.js

@stephenhillier I did a pretty big re-factor as a 1st step before starting edit. I ripped out everything specific to the submission form into it's own component. I think this is a cleaner/better approach. It has some downsides, but I think it's better.
We should merge this bit before I finish the rest, otherwise merging in your changes is going to become very difficult.
- More focused objects
- This approach simplifies things a bit - we don't have as many if this and that and the otherthing and not this thing, e.g.
```
<b-row v-if="!preview && activityType === 'STAFF_EDIT'">
```
becomes:
<b-row v-if="activityType === 'STAFF_EDIT'">
- More events, e.g:
```
v-on:preview="handlePreviewButton"
v-on:resetForm="resetForm"
```
- Thing happening all over the place.

[1104] Re-factor: form and preview split apart

---

app/frontend/src/common/authenticate.js

Added two calls to the Keycloak `updateToken()` method:
* on the `onTokenExpired` event, allowing access tokens to be continually refreshed if user leaves the page open for a long period.
* when loading previously saved tokens from localStorage (such as when returning to the site or refreshing the page).
I believe refresh tokens are valid for 10h.

update Keycloak tokens

---

app/frontend/src/submissions/views/SubmissionsHome.vue

Changed the submission error icon from `X` to `!` as requested.

[1227] change error alert to exclamation mark icon

---

openshift/postgresql.bc.json
openshift/postgresql.dc.json

- set PGCRYPTO_EXTENSION=Y by default
- set POSTGIS_EXTENSION=Y by default
NOTE that I ran the build step separately  (i.e. from a cloned local repo of https://github.com/bcgov/openshift-postgresql-oracle_fdw):
```
oc -n moe-gwells-tools create -f openshift/postgresql96-postgis24-oracle-fdw.sample.bc.json
```

Reference updated postgres image (postgis).

---

app/backend/gwells/views/api.py
app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/common/authenticate.js

Resolved redirect to SSO server issue for invalid redirect URI's
Removed Keycloak from package.json (library did not match SSO server version)
Keycloak now loads from SSO server (this is best practice)
API changed to provide clientId (required for current Keycloak library version served up by SSO server)

[1517] Major re-factor of common/authenticate.js

---

docker-compose.yml

This is currently failing in Docker, so we're temporarily using postgres:9.6.

[1522] PostGIS in Docker Compose

---

openshift/backend.dc.json

Rolling update strategy doesn't work with our mid hook deploy scripts, migrations, etc.

Switch app deploy strategy from rolling back to recreate

---

docker-images/python-gdal/Dockerfile
docker-images/python-gdal/README.md

To support the backend to use GeoDjango and PostGIS, building the external libraries from source.

python-gdal (GEOS, PROJ.4, GDAL)

---

app/frontend/src/submissions/store/index.js
app/frontend/src/submissions/views/SubmissionsHome.vue

- removed params from url that set ordering by well_tag_number. This was causing a static page to be returned. Well tag number is the default ordering for this query anyways.

[1674] Fix Well Tag Search

---

app/backend/gunicorn.cfg

The queries run much slower on our pods than on local - I'm increasing the timeout to find out just how much slower.
Hopefully we can get the time down by optimizing a few things on the database.

Increase the timeout to 60 seconds to allow for query to complete.

---

app/backend/wells/filters.py
app/backend/wells/views.py
tests/api-tests/wells_search_api_tests.json

Previously I used two point fields (sw and ne) to implement the bounding box widget, because that fits in with Django filter nicely, but it generates more complex queries. E.g.
```
SELECT
COUNT(*) AS "__count"
FROM "well" WHERE (
"well"."geom" |&> ST_GeomFromEWKB('\x0101000020e61000006666666666a65ec09a99999999994840'::bytea) 
AND "well"."geom" &> ST_GeomFromEWKB('\x0101000020e61000006666666666a65ec09a99999999994840'::bytea) 
AND "well"."geom" &<| ST_GeomFromEWKB('\x0101000020e610000085eb51b81ea55ec06666666666a64840'::bytea) 
AND "well"."geom" &< ST_GeomFromEWKB('\x0101000020e610000085eb51b81ea55ec06666666666a64840'::bytea))
```
vs using a bounding box filter, which does:
```
SELECT COUNT(*) AS "__count"
FROM "well" WHERE "well"."geom" && …
```

Revert to bounding box style geom filter

---

app/frontend/src/submissions/views/SubmissionsHome.vue

The code is commented temporarily because we may need to implement the intent of the code (prevent saving a change a field's value from `null` to `""` empty string when the user didn't intend to change anything) in a different way.

fix for bug deleting rows of lithology, casings etc

---

openshift/minio.dc.yaml

We needed to provision a new PVC for our prod Minio configuration (`s3/config` directory in the Minio deployment).  I appended v2 to the name of the old PVC.  This PR adds `-v2` to the name of the PVC in the Minio deployment template to keep it consistent with the prod environment.

change name of PVC in Minio template to match prod environment

---

app/frontend/src/common/helpers/formatField.js
app/frontend/src/common/helpers/parseErrors.js
app/frontend/src/submissions/views/SubmissionsHome.vue

This PR includes a map of the most unreadable API field names, and displays a friendlier name to users (in error messages) if possible.

better error messages for submissions/staff edit

---

app/backend/wells/filters.py
tests/api-tests/wells_search_api_tests.json

Changed `well_tag_number=` URL query search on Well search API endpoint to return exact matches only.
This change will impact E-Licensing but is required to better support their app (they require a single exact match when searching by well tag number).

change well_tag_number query behavior to exact match

---

app/frontend/src/submissions/components/SubmissionForm/AquiferData.vue

this fixes a bug that was preventing users from selecting an aquifer on the Well edit page

aquifer select now returns aquifer ID, not an object

---

README.md
app/frontend/jest.config.js

1. Minor fixes to README.md.
2. Changed jest.config.js to use `moduleNameMapper` instead of transform for images (png, etc) to prevent error in `npm run test:unit`.

Minor README.md changes + fixes noise in Jest unit:tests

---

app/frontend/src/aquifers/components/Search.vue

Updated with feedback from Kailee:
>  Testing the enhanced search results works as requested -the page automatically scrolls to the top of the list. However, a search that returns no results leaves the user at the top of the page when there's the opportunity for the same feature; i.e. consistent UX so the page automatically scrolls down to show the "No aquifers could be found" text.

Always scroll to aquifers table after a search completes

---

app/backend/manage.py
docker-compose.yml

Uses Python lib ptvsd to allow a remote debugger to be attached on port 3000. This can enable attaching a VSCode Python debugger to the running Django process.

Allow remote Python debugger to be attached to dev docker container

---

docker-compose.yml

Reduces my Mac's idle CPU usage for docker from 60-70% to 15-20%.

Uses 'cached' consistency check for macOS to lower idle CPU usage.

---

app/frontend/src/aquifers/components/AquiferMap.vue

I updated the legend to show the initially selected cadastral layer on the aquifer summary screen. But I forgot to update the AquiferMap.vue file for the aquifer search map to behave the same.

Adds initially selected cadastral layer to legend on aquifer search map

---

docker-compose.yml

Strangely docker compose on my Linux machine doesn't understand the shorthand volume syntax. I needed to change it to the long form version in order for `docker-compose up` to work.

Use long form for volumes definition so non-macOS OSes can read the docker-compose.yml file

---

.env
app/frontend/src/aquifers/components/View.vue
app/frontend/vue.config.js
docker-compose.yml

Verifying [WATER-540](https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-540) with staging data I saw that the algorithm I was using wasn't working for aquifers with only inactive observation well data (e.g. aquifer #612). I have fixed the algorithm so the display of active and inactive wells shows up for any obs wells data.

540 fix obs wells not displaying inactive wells bug

---

app/backend/gwells/settings/__init__.py

It now will show up when the back-end is running inside a container.

Fixes Django Debug Toolbar

---

app/frontend/package-lock.json
app/frontend/package.json

https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-749
Fixes a bug where you can no longer drag when on a non-vector layer part of the map if you initially click down on a vector layer.

Pins leaflet-gesture-handling npm module

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/aquifers/components/View.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-790
While testing the fix for WATER-790 the map would show a spinner forever.
https://gwells-staging.pathfinder.gov.bc.ca/gwells/aquifers/20
It turns out [Axios had a bug](https://github.com/axios/axios/issues/537) which was still a problem for us even though we were using Axios 0.18.1. Upgrading to 0.19.1 fixes the issue.

Upgrades axios to 0.19.1 to fix Chrome cancellation bug

---

tests/api-tests/aquifers_v2_api_tests.json

Bumps unknown aquifer and well tag numbers up to 999999 in order to not accidentally match a real well or aquifer created on staging.

Fixes staging well aquifer correlation bulk upload API tests

---

app/backend/wells/migrations/0110_delete_legacy_dupes_20200401_2244.py

https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1012
Now the migration will remove the lithology, etc data associated with the duped activity submission instead of just setting the `filing_number` to `NULL`.

Fix dupe removal migration

---

app/frontend/package-lock.json
app/frontend/package.json
app/frontend/src/aquifers/components/SingleAquiferMap.vue
app/frontend/src/aquifers/popup.js

1. Uses [fork of mbgl-gesture-handling](https://github.com/geolonia/mbgl-gesture-handling/pull/7) to use ctrl key instead of alt.
2. Updates well popup to only surround WTN with a link.
3. EMS and Uncorrelated wells layers mouse over tooltips now work when Wells layer is not enabled

Mapbox aquifer details map fixes

---

app/frontend/src/aquifers/components/AquiferMap.vue
app/frontend/src/aquifers/popup.js

Fixes bug where clicking on a EMS or uncorrelated well would not make a popup. Aquifer map uses the ctrl modifier key for mouse wheel zooming.

Mapbox aquifer map fixes

---

app/frontend/src/aquifers/components/Search.vue

https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1103
With a refactor of the Aquifer Search CSS the "Advanced Search" checkboxes were no longer styled properly.
Before:
After:

Fixes CSS bug with aquifer search checkboxes

---

app/frontend/package-lock.json
app/frontend/package.json

https://apps.nrs.gov.bc.ca/int/jira/browse/WATER-1185
Updates to a newer version of mbgl-gesture-handling with a bug fix for ctrl+zoom not working bug.

Fix map zoom bug

---

app/backend/aquifers/views.py
app/backend/gwells/views/api.py
app/backend/registries/urls.py
app/backend/registries/views.py
app/backend/wells/views.py

Simplified documentation to include the following "core" endpoints and get it ready for publishing on DataBC:
* wells list and well details, and public files for wells
* aquifers list and aquifer details, and aquifer documentation
* registries list
New documention:  https://gwells-dev-pr-1799.apps.silver.devops.gov.bc.ca/gwells/api/
the current documentation can be compared here https://apps.nrs.gov.bc.ca/gwells/api/ , feedback welcome on endpoints that should be kept.

clean up API docs and reduce to a simplified set of endpoints

---

app/backend/gwells/documents.py

We are suddenly seeing that spaces in S3 object keys are encoded as plus signs when we list files, but requesting them with the exact same object key as returned by the list operation fails because the plus signs aren't converted back.  So far this is only the case with S3, not Minio.

unquote object names to remove plus signs

---

openshift/docker/backend/Dockerfile

Attempting to download from https://download.osgeo.org results in certificate errors, so I've downgraded it to non-HTTPS instead.

Tweak Dockerfile to download from non-HTTPS url instead

---

app/frontend/src/wells/views/WellDetail.vue

Removed duplicate output from the WellDetail view file.
Contradicting data was an issue caused from data expecting a boolean value where a string stored. (function nullBooleanToYesNo)

Removed duplicate output for alternative specs

---

app/backend/.envrc
app/backend/gwells/authentication.py
app/frontend/src/common/authenticate.js
app/frontend/src/common/store/auth.js
docker-compose.yml

This points the GWELLS application at the Keycloak Gold common realm. Environment variables have been updated to the appropriate values for Gold.
Several fixes have also been made to the Gold-specific code added in previous PRs:
* [Backend] Checking the SSO authority failed due to incorrect string comparison
* [Frontend] Added parameter for PKCE, as Gold requires it (Silver doesn't)
* [Frontend] Look for client roles instead of realm roles

Point GWELLS at Keycloak Gold

---

openshift/ocp4/jobs/export-databc/export.cj.json
openshift/ocp4/jobs/import-licences/import-licences.cj.json
openshift/ocp4/jobs/minio-backup/minio-backup.cj.yaml
openshift/ocp4/jobs/postgres-backup-nfs/postgres-backup.cj.yaml
openshift/ocp4/jobs/update-aquifer/update-aquifer.cj.json

**Background:**
Platform Services recently upgraded the OpenShift Silver cluster to v4.12, which breaks the GWELLS pipeline because it uses a deprecated API that was removed in this version.
Specifically, the `batch/v1beta` API version of Cronjob was deprecated in Kubernetes v1.21 and removed in v4.25 (which OpenShift 4.12 uses).
There are no major changes aside from the change in version name - it seems to mostly be just a promotion from beta to general availability.
**Changes made:**
Replaced `batch/v1beta` with `batch/v1` to reflect this deprecation/removal. That's pretty much it.
**More info:**
* https://docs.openshift.com/container-platform/4.12/release_notes/ocp-4-12-release-notes.html#ocp-4-12-removed-features
* https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-25 …

OpenShift v4.12 upgrade

---

app/backend/gwells/documents.py
app/frontend/src/common/constants.js
app/frontend/src/submissions/components/SubmissionForm/Documents.vue
app/frontend/src/wells/components/Documents.vue

- Changed references in uploaded files from 'Labels' to 'Documents'
- Replaced Date picker and `Date of Action` tag with generative `Upload Date`
- Changed order of form to group fields requiring user input

[GWELLS-2011] FEATURE** Update visuals, change how date is selected

---

app/backend/gwells/documents.py
app/frontend/src/wells/components/Documents.vue

- one date_of_action was leftover causing 1969 date to display in place of "Date Unknown"
- renamed function to reflect being about date of uploads and not date of action

[GWELLS-2011/2013] HOTFIX** correct date_of_action to date_of_uploads

---

app/backend/wells/migrations/0143_attach_attachments_to_wells.py

- Took previously introduced migration and reduced the time complexity to hopefully appease the OOM errors

[GWELLS-2011] HOTFIX** Reduce time complexity on recent migration

---

app/backend/wells/migrations/0143_attach_attachments_to_wells.py

- Previous function did not like being passed in the raw value than the model, this update addresses that (hopeful) fix

[GWELLS-2011] HOTFIX** edit migrations

---

app/backend/wells/management/commands/populate_attachments_count.py
app/backend/wells/views.py

- Creation of Django Command to iterate through all existing files and give proper counts to `well_attachment_count`
- Extension to increment/decrement functionality to create an entry in the `well_attachment_count` table if one does not exist for a given well

[GWELLS-2026] FEATURE** First attempt to create proper counts for attachments

---

app/backend/wells/management/commands/populate_attachments_count.py

[GWELLS-2011] HOTFIX** correct == to <=

---

app/backend/wells/management/commands/update_analysis_method_codes.py
app/backend/wells/management/commands/update_codes.py
app/backend/wells/management/commands/update_pumping_test_description_codes.py
app/backend/wells/migrations/analysis_method_codes.json
app/backend/wells/migrations/pumping_test_description_codes.json
app/frontend/src/wells/views/WellDetail.vue
docker-compose.yml

- Once deployed run `python3 manage.py update_codes` in the `backend` directory for all fields to update
- Created Django commands to update the database codes used in the application (simplifies future updating)
- Added wildcard Django command to run all update_codes script using `update_*_codes.py` format
- Fixed old bug where longform of codes were not loading in `Well Summary` pages if accessed directly
- updated docker-compose pgadmin container name to reduce naming collisions across applications

[GWELLS-2045] BUGFIX/UPDATE** Update dropdown list values, show full name instead of codes

---

app/backend/wells/admin.py
app/backend/wells/models.py
app/backend/wells/views.py
app/frontend/src/wells/views/WellDetail.vue
app/frontend/tests/unit/specs/wells/__snapshots__/WellDetail.spec.js.snap

- refactored code to get licence numbers for a given well. Old code was externally sourced and no longer working
- created WellLicence model since none existed to link to table.
- made well summary licence numbers scalable to multiple licences (from singular)

[GWELLS-2048] BUG FIX** Display Licences in Well Summary

---

app/frontend/src/submissions/views/SubmissionsHome.vue

- Simple (but temporary) hotfix to prevent Pumping Test data from being overwritten
- `aquifer_parameters_set` is not skipped so data is maintained when updating other fields (preventing being overwritten)

[HOTFIX][GWELLS-2070]** maintain aquifer data regardless of changes, prevent overwrite

---

app/frontend/src/common/assets/images/wells-hydraulic.svg
app/frontend/src/common/mapbox/layers.js

- changed the hex value for the halo (stroke) of wells with hydraulic properties from #e29200 to #5dfa57. Values changed in:
app\frontend\src\common\assets\images\wells-hydraulic.svg  
app\frontend\src\common\mapbox\layers.js

[FEATURE][GWELLS-#2053] changed hex colour values for hydraulic wells to be more visible

---

app/frontend/src/common/mapbox/layers.js

Increased circle-stroke-width to make the halo indicating 'aquifer parameters' more noticeable.
In app\frontend\src\common\mapbox\layers.js, changed wellsBaseAndArtesianLayer and searchedWellsLayer to set circle-stroke-width to 2.5 (from 1).
This change makes the map halo around wells that are marked "aquifer parameters" (and "artesian") thicker so that they are more visible.

[FEATURE][GWELLS-2053part2] Increased map well halo width to be more visible

---

app/frontend/src/wells/components/SearchResults.vue
app/frontend/src/wells/components/mixins/filters.js

…tly not sortable.
- Updated sortable keys for the Well data search fields on the front end to reflect whether they are currently sortable.
- Adjusted vertical alignment to account for sortable fields without the sort icons. See screenshots below.

[CHANGE][GWELLS-2087] audit well data search field sortable keys

---

app/backend/gwells/fixtures/wellsearch-codetables.json
app/backend/wells/management/commands/update_drilling_method_codes.py

As 'Dugout' was reported to be inaccurate, changed the description of that drilling method to 'Dug'.
- Created a command **wells\management\commands\update_drilling_method_codes.py** that updates/creates drilling_method_codes that are read from **\gwells\fixtures\wellsearch-codetables.json**. 
- Manually updated the 'description' field in wellsearch-codetables.json (fixed seed data) from 'Dugout' to 'Dug' and ran the command to update the models.
- As all UI elements that display drilling methods use the description for the displayed value, no further changes should be necessary.

[CHANGE][GWELLS-2090] created a command to update/create the description of drilling_method_codes

---

app/backend/wells/serializers_v2.py

- I currently cannot reproduce the issue [locally](http://localhost:8080/gwells/?match_any=true&licenced_status=LICENSED&result_columns=wellTagNumber,identificationPlateNumber,ownerName,streetAddress,legalLot,legalPlan,legalDistrictLot,landDistrict,legalPid,diameter,finishedWellDepth,licenceNumber&limit=10&offset=0&ordering=-well_tag_number#advanced):
- I refactored the get licence number method to use the model layer rather than using raw SQL

[BUG FIX][GWELLS-2104] Refactor get licence number method

---

app/frontend/src/aquifers/components/SingleAquiferMap.vue

For the map legend on the Aquifer Summary page, made it so legend items appear only if a corresponding element is being rendered in the map view. If an element is not being rendered in the view, whether because the zoom level is too low or there are simply no entries present in the search area, the legend will not show an entry for that element.
Updated SingleAquiferMap.vue to do the following:
On the Aquifer Summary page:
- when a map element filter is checked, only update the legend if any of that element is currently being rendered in the map view.
- when the map is moved or zoomed, update the legend to only show elements that are currently being rendered in the map view.
This change affects ***all*** toggle-able map elements, …

[FEATURE[GWELLS-2054] Dynamically Adjust Legend for Aquifer summary map based on elements rendered in view

---

app/frontend/src/aquifers/components/View.vue
app/frontend/tests/unit/specs/aquifers/components/__snapshots__/View.spec.js.snap

changed the popup tooltip for aquifer notations on the aquifer summar…y page to include a link to an info page
- Added some text and a link to the popover tooltip for aquifer notations on the aquifer summary page

[FEATURE][GWELLS-2049] Added a hyperlink to the tool tip description of Aquifer notations on Aquifer Summary page

---

app/backend/.envrc
app/backend/wells/views.py
app/frontend/src/common/constants.js
app/frontend/src/submissions/components/SubmissionForm/Location.vue
app/frontend/src/submissions/components/SubmissionForm/Owner.vue
docker-compose.yml
openshift/backend.dc.json
openshift/ocp4/backend.dc.json

- Added address auto-complete + auto-fill to the Well Owner Information form for well submissions and well editing
- Added address auto-complete + auto-fill to the Well Location form for well submissions and well editing
Utilized the BC Gov Geocoder API to get addresses. This API allows 1000 requests/min so no throttling should occur. BUT, it does not have Postal Code information, so Postal Code is not auto-filled.

[FEATURE][GWELLS-2094] Address autofill/autocomplete added to Well Owner and Well Location forms

---

app/backend/wells/urls.py
app/backend/wells/views.py
app/frontend/src/common/services/ApiService.js
app/frontend/src/submissions/components/SubmissionForm/Location.vue
app/frontend/src/submissions/components/SubmissionForm/Owner.vue
docker-compose.yml
openshift/backend.dc.json
openshift/ocp4/backend.dc.json

Reverts bcgov/gwells#2111 as there are bugs that prevents driller from saving address during submission.
Issues identified by Su:
It seems like disappeared after clicked "submit and review" button  or "submit" button on the report submission page, the address (both well owner and well location) kept blank in the review "well report submission page" or after submission  (well summary page) even it is by manual entry only
also on well editing page, my editing action in the Owner's mailing address or well location street address won't active the "save" button

Revert "[FEATURE][GWELLS-2094] Address autofill/autocomplete added to Well Owner and Well Location forms"

---

app/backend/wells/urls.py
app/backend/wells/views.py
app/frontend/src/common/services/ApiService.js
app/frontend/src/submissions/components/SubmissionForm/Location.vue
app/frontend/src/submissions/components/SubmissionForm/Owner.vue
docker-compose.yml
openshift/backend.dc.json
openshift/ocp4/backend.dc.json

Added address auto-complete + auto-fill to the Well Owner Information form for well submissions and well editing
Added address auto-complete + auto-fill to the Well Location form for well submissions and well editing
Utilized the BC Gov Geocoder API to get addresses. This API allows 1000 requests/min so no throttling should occur. BUT, it does not have Postal Code information, so Postal Code is not auto-filled.

[FEATURE][GWELLS-2094-4] Address autofill/autocomplete added to Well Owner and Well Location forms

---

app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue
app/frontend/src/submissions/components/SubmissionForm/Coords.vue
app/frontend/src/submissions/components/SubmissionForm/CoordsMap.vue
app/frontend/src/submissions/views/SubmissionsHome.vue

- Allow user creating new well to place initial map marker with `click` action
- Can only click initial action to reduce maps coordinates being accidentally overwritten in edit
- In new well submission, check Lat Long exist and are within British Columbia
- Highlight message about map placements

[GWELLS-2093] FEATURE** Gwells 2093 lat long validation checks + point n click map

---

app/backend/aquifers/fixtures/aquifers.json
app/backend/wells/serializers_v2.py

…eturned unique.
- To replicate the issue seen in staging and production I have updated the aquifers fixture JSON to include a water rights licence with multiple purposes. Specifically another water rights licence with the same licence number but a different purpose.
- Updated the well list serializer to return only unique licence numbers.
After replicating but before fix:
After bug fix:

[BUG][GWELLS-2104] Return unique licence numbers

---

app/frontend/src/submissions/views/SubmissionsHome.vue

- Check if the `$ref.ActivitySubmission` exists for form validation
- Fix the error where isFormValid() is called on the final Submit where the component isn't rendered on the page (but the coordinates are valid and were submitted in the previous step).

[HOTFIX][GWELLS-#2132] - Check if the $ref exists for activitySubmission, bug fix on Submit

---

README.md
app/backend/gwells/views/bulk.py

- Fixed aquifer number reversion by adding aquifer change information to activity submission and fields provided table during a bulk update

[BUG][Gwells-2108]

---

app/backend/aquifers/urls.py
app/backend/aquifers/views_v2.py
app/backend/gwells/management/commands/export_databc.py
app/backend/wells/urls.py
app/backend/wells/views.py

- Added `/api/v2/gis/aquifer-parameters` endpoint to gwells api for exporting public data to DataBC
- Most of the functionality is duplicated from other DataBC exports
- endpoints use `realtime=True` query string to pull live data vs stored date (existing functionality in previous export endpoints)

[GWELLS-2050] FEATURE** Date export Endpoint DataBC

---

app/frontend/src/submissions/views/SubmissionsHome.vue

- removed well_tag_no and pumping_test_no from payload during staff_edit to prevent none from appearing in the change history

[FIX][GWELLS-2122] - FIX CHANGE HISTORY

---

app/backend/registries/views.py

- Updated API to move "Regional District of" to the end of a substring in the `/gwells/registries` page
- Response uses uuids for search, so no further changes needed
- [Dev realm](https://gwells-dev-pr-2157.apps.silver.devops.gov.bc.ca/gwells/registries)
- The `Dev` realm test data is inconsistent to `staging`, using the regions filter won't properly display data because of it
- This is consistent across `dev` realms, and it not a result of these changes
- The behaviour functions as expected when using in Staging
- You can browse the network in dev tools to witness its using a uuid for search, and not the `name` string
API Object
Request Headers
Before Change
After Change

[GWELLS-2024] FEATURE** Change regional area keys in API response

---

docker-compose.yml

- removed `consistency: cached` which was added in [PR #1487](https://github.com/bcgov/gwells/pull/1487) & [PR #1476](https://github.com/bcgov/gwells/pull/1476). These PRs are over 4 years old. (Times have changed)
- Removing this allowed hotloading to continue, but with the previously forewarned high CPU rates (sometimes > 90%) 
- removed `CHOKIDAR_USEPOLLING` added in [PR #923](https://github.com/bcgov/gwells/pull/923). 5+ year old PR at this time
-  It seems this is a method of checking for file changes, When I removed it the containers still hot reloaded appropriately, but even with mass editing and saving I cannot get my CPU >41%. Idle time has typically been hanging <2%.

[GWELLS-2162] DEV** Get hotloading running in the frontend container

---

Makefile
tests/api-tests/.envrc
tests/api-tests/README.md
tests/api-tests/local_aquifers.sh
tests/api-tests/local_registries.sh
tests/api-tests/local_run_all.sh
tests/api-tests/local_submissions.sh
tests/api-tests/local_wells.sh
tests/api-tests/local_wells_search.sh
tests/api-tests/runnewman.sh
tests/api-tests/wells_search_api_tests.json
tests/api-tests/wells_search_v2_api_tests.json

- Updated Makefile to run API tests locally with "make api-tests-local"
- Command can run individual tests suites with additional arg `TEST_FILE=<testfile.sh>`
- Updated `local_run_all.sh` to do the following
- Run all tests wild carded with `local_*.sh`.
- Load in environment variables from `.envrc`
- Stop if permissions fail on a file
- Update all test suites to run standalone (load env's if not already present)
- Update Wiki section on Testing
- Update README in api-tests.
- Modified the test suites to use `decodeURIComponent()` on values. This was causing tests to fail locally that would pass in Jenkins (%20 taking the place if whitespace in comparisons).
**All tests now pass locally AND in Jenkins** *(previously only Jenkins)*

[GWELLS-2142] TESTS** Update API-Testing Files, bash scripts, MAKE command

---

app/backend/gwells/views/bulk.py

To address ticket #2108 , we recommended that all bulk updates be rerun, in order for the fix to take place (adding entries in activity_submissions and fields_provided). However, we did not account for the fact that redoing bulk updates would skip updating wells where the reversion had NOT YET occurred.
changed views/bulk.py to NOT ignore wells where the aquifer is NOT changing. This will make it so redoing bulk updates will fix the reversion.
This change should only be temporary and should be reverted once all historical bulk updates have been redone.

[BUG][GWELLS-2173] temporary fix for aquifer reversion from bulk updates

---

Makefile
app/backend/registries/views.py
app/frontend/src/common/store/auth.js
app/frontend/src/registry/components/people/Notes.vue
app/frontend/tests/unit/specs/people/Notes.spec.js

- Added Get/Patch/Delete functionality to the GWELLS `organizations/{id}/notes/{note_id}` endpoint
- Updated frontend to make use of new crud functionality
- Added Modals for editing and deleting notes
- Add a Edit flag to the note body to highlight if a user has updated a note at any time
Auth considerations:
- Only user who submits note can edit a note
- Creation User and Administrators can delete notes
**How to access:**
1. Log into Gwells
2. Select 'Registry Search' from nav bar
3. Select 'Manage Companies' from admin options
4. Select a company
Previous notes section:
New note section:
Edit Modal:
Delete Modal:

[GWELLS-2197] FEATURE** CRUD operations for Organizations Notes

---

app/backend/registries/serializers.py
app/backend/registries/views.py
app/frontend/src/registry/components/people/Notes.vue
app/frontend/src/registry/components/people/PersonDetail.vue
app/frontend/src/registry/components/people/PersonNotes.vue
app/frontend/tests/unit/specs/people/PersonDetail.spec.js
app/frontend/tests/unit/specs/people/PersonNotes.spec.js

This PR is an expansion on the work done on [[GWELLS-2197]](https://github.com/bcgov/gwells/pull/2206) but targetting the `Persons` section of the application
- Added Get/Patch/Delete functionality to the GWELLS `drillers/{id}/notes/{note_id}` endpoint
- Updated frontend to make use of new crud functionality 
- Added Modals for editing and deleting notes
- Add a Edit flag to the note body to highlight if a user has updated a note at any time
Auth considerations:
- Only user who submits note can edit a note
- Creation User and Administrators can delete notes
**How to access:**
1. Log into Gwells
2. Select 'Registry Search' from nav bar
3. Search for driller
4. Select a driller from results

[GWELLS-2198] FEATURE** CRUD Functionality for Persons Notes

---

app/backend/gwells/templates/gwells/base_spa.html
app/frontend/src/aquifers/components/View.vue
app/frontend/src/aquifers/store/search.js
app/frontend/src/main.js
app/frontend/src/wells/components/SearchResultExports.vue

- Commenting out most references to Google Analytics. Even though there is an env var to disable GA, there is still js created. This change is to ensure that Matomo analytics continue to function without GA code. As prod is the only place that the Matomo analytics is working, decided on this path as most expedient way to test.

[CHANGE][GWELLS-2186] Commenting out Google Analytics

---

app/backend/gwells/templates/gwells/base_spa.html
app/frontend/src/aquifers/components/View.vue
app/frontend/src/aquifers/store/search.js
app/frontend/src/main.js
app/frontend/src/wells/components/SearchResultExports.vue

Reverts bcgov/gwells#2217. This change was testing if Matomo tracking worked with all of the Google Analytics code commented out. This showed that the current implementation of Matomo does NOT work without the GA code.

Revert "[CHANGE][GWELLS-2186] Commenting out Google Analytics"

---

Makefile
app/backend/wells/tests/test_signals.py

- Add tests for wells signals
- Update Makefile test-django rule to allow providing a path, for testing individual test files and individual tests.

[CHANGE][GWELLS-2189] Add well signals tests

---

app/frontend/src/submissions/views/SubmissionsHome.vue

- Previous fix to an old bug was checking if $ref existed before continuing (on submission page), the check didn't check for the sub $ref which affected single page viewing leading to the confirmation modal.

[GWELLS-NA] Fix Single page submission

---

.gitignore
app/.s2i/bin/assemble
app/frontend/package-lock.json
app/scripts/backend-command-script.sh

When running docker-compose up in local, the following error is generated in the backend container : Could not fetch URL https://pypi.python.org/simple/pip/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852) , and the backend does not run.
- One solution is to add trusted host flags when upgrading pip seen [here](https://stackoverflow.com/questions/25981703/pip-install-fails-with-connection-error-ssl-certificate-verify-failed-certi). As manually assigning trusted hosts is not an ideal solution,
a solution was found that did not require their use.

[FIX][GWELLS-2226] fix docker compose is generating an error in local

---

.github/codeowners

Codeowners file!  Anyone listed inside will be notified for PRs matching a pattern.  The one here is `*`, matching everything.  Later on we can potentially limit reviews to just codeowners.

chore(ci): codeowners

---

app/frontend/src/submissions/views/SubmissionsHome.vue

- Changed formIsFlat value in SubmissionsHome.vue from false (multi-page) to true (single-page) for default on load

[Change] [GWELLS-#2218] Well Submission Defaults to Single Page

---

app/frontend/tests/unit/specs/submissions/SubmissionsHome.spec.js

The previous changes under `ticket 2218` changed the state of the submission form at load. 
The new state causes the test to fail, as it wasn't designed with the full form in mind. As the test is no longer applicable, and we have longstanding plans to rewrite our test suite once the dependency updates are completed, I am removing the test.
*nature is healing*

[GWELLS-2218] FIX** remove broken test from suite

---

app/frontend/src/wells/components/SearchResults.vue

- changed css for searchResultsTable.td.data to wrap instead of nowrap
- ![image](https://github.com/bcgov/gwells/assets/127158867/ac87e49b-b114-443e-9030-61694a5767c6)
- <img width="1156" alt="Screenshot 2024-06-21 at 9 24 12 AM" src="https://github.com/bcgov/gwells/assets/127158867/b1c56fcd-4c4d-48dc-88e0-a824f6defc00">

[GWELLS-2239] FIX/text wrap on well results

---

app/frontend/src/submissions/components/SubmissionForm/ActivitySubmissionForm.vue

- Added `bg-warning` class to text "All form fields marked with a trailing asterisk are mandatory fields." on [Submit Report](https://gwells-staging.apps.silver.devops.gov.bc.ca/gwells/submissions) page.
- ![image](https://github.com/bcgov/gwells/assets/127158867/d3954a3d-3d79-417c-a6b0-a9d2b688fca5)
- ![Screenshot 2024-07-09 at 3 42 46 PM](https://github.com/bcgov/gwells/assets/127158867/d50af518-fe8e-4844-bc05-06e761200f54)

[GWELLS-2263] FIX** Add Warning Class to Text on Submission Form

---

app/frontend/src/wells/components/SearchColumnSelect.vue
app/frontend/src/wells/components/SearchResults.vue

Saves the user's column preferences to local storage to ensure they persist across sessions, including when the user logs out, refreshes the page, or closes and reopens the app.
- Saves user column preferences to local storage.
- Sets columns to local storage values upon refresh if they exist, otherwise falls back to default values.

[GWELLS-2265] Feature** Stores user column preferences in local storagre

---

app/frontend/src/wells/components/SearchColumnSelect.vue
app/frontend/src/wells/store/index.js

- Saves the user's column preferences to local storage to ensure they persist across sessions, including when the user logs out, refreshes the page, or closes and reopens the app.
- Fixes issue where columns reset to default after user logout.

[GWELLS-2265] HOTFIX** Fix issue with logout/login

---

app/frontend/src/wells/components/SearchResults.vue

Added CSS to make the search results header sticky so the user can always see the columns.
-Updated SearchResults.vue to add a .sticky-header class to the <thead> element.
If you look in the photo you can see that the rows now scroll behind the headers while they remain stuck at the top:

[GWELLS-2268] Styling** Added CSS to make search result header sticky

---

app/frontend/src/common/mapbox/layers.js

- Change of aquifer line and fill colour to Hex #686868 (green)
- Before change cadastral and aquifers were both orange ![Screenshot 2024-08-06 at 2 10 58 PM](https://github.com/user-attachments/assets/96856568-dc0d-4bf3-ba13-0ba5e781e69e)
- ![Screenshot 2024-08-06 at 2 08 54 PM](https://github.com/user-attachments/assets/44339a02-88e2-4c1a-982c-62f28672b54f)
- On Hover ![Screenshot 2024-08-06 at 2 09 00 PM](https://github.com/user-attachments/assets/dc5136f0-55df-4a8c-b22f-35510ea8a068)
- Searched aquifer still shows as purple while others are now green instead of orange ![Screenshot 2024-08-06 at 2 10 36 PM](https://github.com/user-attachments/assets/7d44b987-9bd4-4810-8e10-d810ae6cd321)

[GWELLS-2270] FIX** Change to aquifer colour
